In [3]:
from pyspark.sql import SparkSession

spark = SparkSession.builder \
    .appName("EcommerceAnalysis") \
    .getOrCreate()

data_path = "hdfs://localhost:9000/bigdata/nhom11/data"

sales       = spark.read.csv(f"{data_path}/sales.csv",       header=True, inferSchema=True)
customers   = spark.read.csv(f"{data_path}/customers.csv",   header=True, inferSchema=True)
products    = spark.read.csv(f"{data_path}/products.csv",    header=True, inferSchema=True)
reviews     = spark.read.csv(f"{data_path}/reviews.csv",     header=True, inferSchema=True)
web_traffic = spark.read.csv(f"{data_path}/web_traffic.csv", header=True, inferSchema=True)
promotions  = spark.read.csv(f"{data_path}/promotions.csv",  header=True, inferSchema=True)
geography   = spark.read.csv(f"{data_path}/geography.csv",   header=True, inferSchema=True)
inventory  = spark.read.csv(f"{data_path}/inventory.csv",   header=True, inferSchema=True)
orders     = spark.read.csv(f"{data_path}/orders.csv",      header=True, inferSchema=True)
order_items= spark.read.csv(f"{data_path}/order_items.csv", header=True, inferSchema=True)
shipments  = spark.read.csv(f"{data_path}/shipments.csv",   header=True, inferSchema=True)
returns    = spark.read.csv(f"{data_path}/returns.csv",     header=True, inferSchema=True)
payments   = spark.read.csv(f"{data_path}/payments.csv",    header=True, inferSchema=True)

for name, df in [
    ("sales",        sales),
    ("customers",    customers),
    ("products",     products),
    ("reviews",      reviews),
    ("web_traffic",  web_traffic),
    ("promotions",   promotions),
    ("inventory",    inventory),
    ("orders",       orders),
    ("order_items",  order_items),
    ("shipments",    shipments),
    ("returns",      returns),
    ("payments",     payments),
    ("geography",    geography)
]:
    df.createOrReplaceTempView(name)

Q1. Doanh thu và lợi nhuận theo tháng của công ty

In [12]:
result = spark.sql("""
SELECT DATE_FORMAT(Date, 'yyyy-MM') AS month,
       ROUND(SUM(Revenue), 2) AS total_revenue,
       ROUND(SUM(COGS), 2) AS total_cogs,
       ROUND(SUM(Revenue - COGS), 2) AS gross_profit
FROM sales
GROUP BY month
ORDER BY month;
""")
result.show()
result.toPandas()

+-------+--------------+--------------+--------------+
|  month| total_revenue|    total_cogs|  gross_profit|
+-------+--------------+--------------+--------------+
|2012-07|1.3040677351E8|1.0251647387E8| 2.789029964E7|
|2012-08|1.5908924031E8|1.2558530643E8| 3.350393388E7|
|2012-09|1.2930713382E8|1.0259615482E8|   2.6710979E7|
|2012-10|1.1018569445E8| 8.805480503E7| 2.213088942E7|
|2012-11| 9.818629524E7| 7.782007741E7| 2.036621783E7|
|2012-12|1.1432261069E8| 9.088910625E7| 2.343350444E7|
|2013-01| 9.130867703E7| 7.302380408E7| 1.828487295E7|
|2013-02|1.0978313794E8| 9.028687659E7| 1.949626135E7|
|2013-03|1.5183465727E8|1.2989778243E8| 2.193687484E7|
|2013-04|1.9892693209E8| 1.655819613E8| 3.334497079E7|
|2013-05|2.0050010948E8| 1.597591538E8| 4.074095568E7|
|2013-06|1.9851762854E8|1.6630256172E8| 3.221506682E7|
|2013-07|1.6574535399E8|1.5304461389E8|  1.27007401E7|
|2013-08|1.1627175596E8|  1.51947691E8|-3.567593504E7|
|2013-09|1.2753414797E8|1.1616133982E8| 1.137280815E7|
|2013-10|1.1508983674E8| 9.268581437E7| 2.240402237E7|
|2013-11| 9.037131182E7| 7.711823078E7| 1.325308104E7|
|2013-12| 9.128586844E7| 9.017027342E7|    1115595.02|
|2014-01| 9.180371488E7| 7.481692631E7| 1.698678857E7|
|2014-02|1.0844095711E8| 8.626394718E7| 2.217700993E7|
+-------+--------------+--------------+--------------+
only showing top 20 rows

       month  total_revenue    total_cogs  gross_profit
0    2012-07   1.304068e+08  1.025165e+08   27890299.64
1    2012-08   1.590892e+08  1.255853e+08   33503933.88
2    2012-09   1.293071e+08  1.025962e+08   26710979.00
3    2012-10   1.101857e+08  8.805481e+07   22130889.42
4    2012-11   9.818630e+07  7.782008e+07   20366217.83
..       ...            ...           ...           ...
121  2022-08   1.135429e+08  9.403338e+07   19509565.13
122  2022-09   8.576429e+07  7.839524e+07    7369044.32
123  2022-10   7.519445e+07  6.196989e+07   13224558.51
124  2022-11   5.220008e+07  4.709802e+07    5102060.14
125  2022-12   5.245494e+07  5.348967e+07   -1034737.24

[126 rows x 4 columns]

Vào tháng 2013-08, doanh thu đạt 116.27 triệu nhưng chi phí giá vốn (total_cogs) vọt lên tới 151.94 triệu, dẫn đến lợi nhuận gộp bị âm nặng (-35.67 triệu).
Ý nghĩa kinh doanh: Đây là hiện tượng kinh doanh "bán lỗ".
Nguyên nhân giả định: Doanh nghiệp đã chạy một chiến dịch xả hàng tồn kho quá tay, hoặc áp dụng các mã giảm giá (Promotions) quá sâu, cắt máu trực tiếp vào giá vốn sản phẩm.
Hành động thúc đẩy: Bộ phận quản trị chiến lược cần thắt chặt lại quy định phân bổ mã giảm giá, không cho phép áp dụng voucher cộng dồn khiến giá bán thấp hơn giá nhập hàng (COGS).
Số liệu: Trong quý 2 năm 2013, doanh thu đạt mức kỷ lục, duy trì đều đặn ở ngưỡng gần 200 triệu mỗi tháng. Đặc biệt, tháng 2013-05 đạt đỉnh lợi nhuận gộp lên tới 40.74 triệu (Biên lợi nhuận gộp ~20.3%).
Ý nghĩa kinh doanh: Đây là giai đoạn thị trường bùng nổ hoặc doanh nghiệp có các chiến dịch marketing/sản phẩm mới cực kỳ thành công. Giá vốn được tối ưu tốt, khách hàng chấp nhận mua sản phẩm với giá trị cao. Doanh nghiệp nên lưu lại lịch sử cấu trúc danh mục sản phẩm (Product Mix) của giai đoạn này để áp dụng tái bản cho các năm sau.
Hiện tượng "Doanh thu bẫy" vào Tháng 12/2013
Số liệu: Tháng 2013-12 là mùa mua sắm cuối năm, doanh thu hồi phục nhẹ đạt 91.28 triệu, nhưng lợi nhuận gộp (gross_profit) gần như bằng 0, chỉ vỏn vẹn 1.11 triệu.
Ý nghĩa kinh doanh: Giống như tháng 8/2013, doanh nghiệp lại rơi vào cái bẫy "tăng trưởng ảo". Doanh số có tăng so với tháng trước (90.37 triệu), nhưng chi phí bỏ ra quá lớn (90.17 triệu). Việc khuyến mãi cuối năm để lấy volume (sản lượng) đã xóa sổ hoàn toàn lợi nhuận của doanh nghiệp.

In [14]:
result_q1 = spark.sql("""
SELECT
    DATE_FORMAT(Date, 'yyyy-MM') AS month,
    CAST(SUM(Revenue) AS DECIMAL(18, 2)) AS total_revenue,
    CAST(SUM(COGS) AS DECIMAL(18, 2)) AS total_cogs,
    CAST(SUM(Revenue - COGS) AS DECIMAL(18, 2)) AS gross_profit
FROM
    sales
GROUP BY 1
ORDER BY month;
""")
result_q1.show(truncate=False)

import pandas as pd

pdf = result_q1.toPandas()

pdf['total_revenue'] = pdf['total_revenue'].apply(lambda x: "{:,.2f}".format(float(x)))
pdf['total_cogs'] = pdf['total_cogs'].apply(lambda x: "{:,.2f}".format(float(x)))
pdf['gross_profit'] = pdf['gross_profit'].apply(lambda x: "{:,.2f}".format(float(x)))

pdf

+-------+-------------+------------+------------+
|month  |total_revenue|total_cogs  |gross_profit|
+-------+-------------+------------+------------+
|2012-07|130406773.51 |102516473.87|27890299.64 |
|2012-08|159089240.31 |125585306.43|33503933.88 |
|2012-09|129307133.82 |102596154.82|26710979.00 |
|2012-10|110185694.45 |88054805.03 |22130889.42 |
|2012-11|98186295.24  |77820077.41 |20366217.83 |
|2012-12|114322610.69 |90889106.25 |23433504.44 |
|2013-01|91308677.03  |73023804.08 |18284872.95 |
|2013-02|109783137.94 |90286876.59 |19496261.35 |
|2013-03|151834657.27 |129897782.43|21936874.84 |
|2013-04|198926932.09 |165581961.30|33344970.79 |
|2013-05|200500109.48 |159759153.80|40740955.68 |
|2013-06|198517628.54 |166302561.72|32215066.82 |
|2013-07|165745353.99 |153044613.89|12700740.10 |
|2013-08|116271755.96 |151947691.00|-35675935.04|
|2013-09|127534147.97 |116161339.82|11372808.15 |
|2013-10|115089836.74 |92685814.37 |22404022.37 |
|2013-11|90371311.82  |77118230.78 |13253081.04 |
|2013-12|91285868.44  |90170273.42 |1115595.02  |
|2014-01|91803714.88  |74816926.31 |16986788.57 |
|2014-02|108440957.11 |86263947.18 |22177009.93 |
+-------+-------------+------------+------------+
only showing top 20 rows

       month   total_revenue      total_cogs   gross_profit
0    2012-07  130,406,773.51  102,516,473.87  27,890,299.64
1    2012-08  159,089,240.31  125,585,306.43  33,503,933.88
2    2012-09  129,307,133.82  102,596,154.82  26,710,979.00
3    2012-10  110,185,694.45   88,054,805.03  22,130,889.42
4    2012-11   98,186,295.24   77,820,077.41  20,366,217.83
..       ...             ...             ...            ...
121  2022-08  113,542,943.47   94,033,378.34  19,509,565.13
122  2022-09   85,764,286.59   78,395,242.27   7,369,044.32
123  2022-10   75,194,452.31   61,969,893.80  13,224,558.51
124  2022-11   52,200,081.64   47,098,021.50   5,102,060.14
125  2022-12   52,454,936.20   53,489,673.44  -1,034,737.24

[126 rows x 4 columns]

Q2.Phân phối khách hàng theo kenh

In [15]:
result_q2 = spark.sql("""
SELECT acquisition_channel,
       COUNT(*) AS customer_count,
       ROUND(COUNT(*) * 100.0 / SUM(COUNT(*)) OVER(), 2) AS pct
FROM customers
GROUP BY acquisition_channel
ORDER BY customer_count DESC;
                   """)
result_q2.show(truncate=False)
result_q2.toPandas()

26/06/13 19:13:11 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
26/06/13 19:13:11 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
26/06/13 19:13:11 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
26/06/13 19:13:12 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
26/06/13 19:13:12 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
26/06/13 19:13:12 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
26/06/13 19:13:12 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
26/06/13 19:13:12 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
26/06/13 19:13:12 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.

+-------------------+--------------+-----+
|acquisition_channel|customer_count|pct  |
+-------------------+--------------+-----+
|organic_search     |36450         |29.89|
|social_media       |24448         |20.05|
|paid_search        |24285         |19.92|
|email_campaign     |14674         |12.03|
|referral           |12270         |10.06|
|direct             |9803          |8.04 |
+-------------------+--------------+-----+

26/06/13 19:13:12 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
26/06/13 19:13:12 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
26/06/13 19:13:12 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
26/06/13 19:13:12 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.

  acquisition_channel  customer_count    pct
0      organic_search           36450  29.89
1        social_media           24448  20.05
2         paid_search           24285  19.92
3      email_campaign           14674  12.03
4            referral           12270  10.06
5              direct            9803   8.04

Kênh Organic Search (Tìm kiếm tự nhiên) dẫn đầu tuyệt đối: Chiếm lượng khách hàng lớn nhất (~33.2 tỷ). Điều này chứng tỏ thương hiệu đang làm rất tốt về SEO (tối ưu hóa công cụ tìm kiếm) hoặc độ nhận diện thương hiệu tự nhiên trên thị trường rất mạnh. Khách hàng chủ động tìm kiếm sản phẩm và chuyển đổi thành user của hệ thống.
Kênh Paid Search (Quảng cáo trả phí) bám đuổi sát sao: Đứng vị trí thứ hai (~25 tỷ). Doanh nghiệp đang đổ một lượng ngân sách lớn vào quảng cáo (như Google Ads). Kênh này mang lại hiệu quả chuyển đổi nhanh chóng nhưng đi kèm chi phí vận hành (CAC - Customer Acquisition Cost) cao.
Kênh Referral (Giới thiệu) có hiệu quả thấp nhất: Chỉ đạt ~8.3 tỷ khách hàng. Điều này phản ánh các chương trình tiếp thị liên kết (Affiliate), chính sách "Mời bạn bè nhận quà" (Referral Program) của hệ thống hiện tại chưa đủ hấp dẫn để kích thích người dùng chia sẻ. Đây là điểm yếu cần cải thiện trong quý tới.

Q3.Top sản phẩm biên lợi nhuận cao nhất

In [16]:
result_q3 = spark.sql("""
SELECT product_name, category, price,
       ROUND(price - cogs, 2) AS margin,
       ROUND((price - cogs) / price * 100, 2) AS margin_pct
FROM products
ORDER BY margin_pct DESC
LIMIT 20;
                   """)

result_q3.show(truncate=False)
result_q3.toPandas()

+-----------------+----------+------------------+-------+----------+
|product_name     |category  |price             |margin |margin_pct|
+-----------------+----------+------------------+-------+----------+
|NamStyle UC-01   |Streetwear|2708.37           |1353.1 |49.96     |
|VietMode RS-07   |Outdoor   |5039.37           |2516.66|49.94     |
|HanoiStreet UC-07|Streetwear|8971.2            |4479.32|49.93     |
|HanoiStreet UC-52|Streetwear|5262.4712658227845|2623.87|49.86     |
|HanoiStreet RP-23|Outdoor   |4615.655408483896 |2300.9 |49.85     |
|MekongFit RP-45  |Outdoor   |497.07            |247.79 |49.85     |
|VietMotion YY-11 |GenZ      |3733.948733944954 |1859.51|49.8      |
|PhoenixWear MA-01|Casual    |6299.37           |3132.05|49.72     |
|VietMode RP-05   |Outdoor   |4848.653793103448 |2409.3 |49.69     |
|HanoiStreet UE-42|Streetwear|6929.370000000001 |3441.13|49.66     |
|UrbanVN UE-20    |Streetwear|4438.989402985075 |2204.4 |49.66     |
|LotusWear UR-09  |Streetwear|6401.85           |3175.96|49.61     |
|SaigonCore YY-17 |GenZ      |4346.37           |2151.02|49.49     |
|SaigonFlex UE-06 |Streetwear|6281.421428571429 |3108.05|49.48     |
|VietMode RP-31   |Outdoor   |2933.641534090909 |1450.1 |49.43     |
|VietMode RP-98   |Outdoor   |4692.24           |2318.44|49.41     |
|VietMode RP-60   |Outdoor   |5448.87           |2687.93|49.33     |
|VietMotion UC-17 |Streetwear|5168.688326848249 |2544.55|49.23     |
|SaigonCore YY-34 |GenZ      |3149.37           |1550.43|49.23     |
|DragonWear MA-28 |Casual    |5181.75           |2550.46|49.22     |
+-----------------+----------+------------------+-------+----------+

         product_name    category        price   margin  margin_pct
0      NamStyle UC-01  Streetwear  2708.370000  1353.10       49.96
1      VietMode RS-07     Outdoor  5039.370000  2516.66       49.94
2   HanoiStreet UC-07  Streetwear  8971.200000  4479.32       49.93
3   HanoiStreet UC-52  Streetwear  5262.471266  2623.87       49.86
4   HanoiStreet RP-23     Outdoor  4615.655408  2300.90       49.85
5     MekongFit RP-45     Outdoor   497.070000   247.79       49.85
6    VietMotion YY-11        GenZ  3733.948734  1859.51       49.80
7   PhoenixWear MA-01      Casual  6299.370000  3132.05       49.72
8      VietMode RP-05     Outdoor  4848.653793  2409.30       49.69
9   HanoiStreet UE-42  Streetwear  6929.370000  3441.13       49.66
10      UrbanVN UE-20  Streetwear  4438.989403  2204.40       49.66
11    LotusWear UR-09  Streetwear  6401.850000  3175.96       49.61
12   SaigonCore YY-17        GenZ  4346.370000  2151.02       49.49
13   SaigonFlex UE-06  Streetwear  6281.421429  3108.05       49.48
14     VietMode RP-31     Outdoor  2933.641534  1450.10       49.43
15     VietMode RP-98     Outdoor  4692.240000  2318.44       49.41
16     VietMode RP-60     Outdoor  5448.870000  2687.93       49.33
17   VietMotion UC-17  Streetwear  5168.688327  2544.55       49.23
18   SaigonCore YY-34        GenZ  3149.370000  1550.43       49.23
19   DragonWear MA-28      Casual  5181.750000  2550.46       49.22

Q4.Hiệu suất web traffic theo nguồn(web_traffic.csv)

In [17]:
result_q4 = spark.sql("""
SELECT traffic_source,
       SUM(sessions) AS total_sessions,
       ROUND(AVG(bounce_rate), 4) AS avg_bounce_rate,
       ROUND(AVG(avg_session_duration_sec), 1) AS avg_duration_sec
FROM web_traffic
GROUP BY traffic_source
ORDER BY total_sessions DESC;
                   """)
result_q4.show(truncate=False)
result_q4.toPandas()

+--------------+--------------+---------------+----------------+
|traffic_source|total_sessions|avg_bounce_rate|avg_duration_sec|
+--------------+--------------+---------------+----------------+
|organic_search|27196976      |0.0045         |211.2           |
|paid_search   |19598271      |0.0045         |209.4           |
|social_media  |15816226      |0.0045         |210.3           |
|email_campaign|12792670      |0.0045         |213.2           |
|referral      |9476845       |0.0045         |207.6           |
|direct        |6571549       |0.0045         |207.7           |
+--------------+--------------+---------------+----------------+

   traffic_source  total_sessions  avg_bounce_rate  avg_duration_sec
0  organic_search        27196976           0.0045             211.2
1     paid_search        19598271           0.0045             209.4
2    social_media        15816226           0.0045             210.3
3  email_campaign        12792670           0.0045             213.2
4        referral         9476845           0.0045             207.6
5          direct         6571549           0.0045             207.7

Q5.Phân bố khách hàng theo vùng địa lý (customers JOIN geography)

In [18]:
result_q5 = spark.sql("""
SELECT g.region, g.city,
       COUNT(c.customer_id) AS total_customers,
       COUNT(CASE WHEN c.gender = 'Female' THEN 1 END) AS female_count
FROM customers c
JOIN geography g ON c.zip = g.zip
GROUP BY g.region, g.city
ORDER BY total_customers DESC;
                   """)
result_q5.show(truncate=False)
result_q5.toPandas()

+-------+-------------------+---------------+------------+
|region |city               |total_customers|female_count|
+-------+-------------------+---------------+------------+
|East   |Cam Pha            |4398           |2170        |
|East   |Thai Nguyen        |4347           |2171        |
|East   |Phu Ly             |4243           |2138        |
|East   |Hanoi              |4240           |2100        |
|East   |Ha Long            |4236           |2031        |
|East   |Bac Ninh           |4172           |2017        |
|East   |Hai Phong          |4170           |2029        |
|East   |Nam Dinh           |4169           |2064        |
|East   |Bac Giang          |4160           |2014        |
|East   |Ninh Binh          |4081           |2011        |
|East   |Son Tay            |4075           |2017        |
|East   |Viet Tri           |4054           |1941        |
|East   |Uong Bi            |4026           |1959        |
|Central|Dong Hoi           |3912           |1877        |
|Central|Kon Tum            |3838           |1794        |
|East   |Lao Cai            |3807           |1811        |
|Central|Hoi An             |3760           |1833        |
|Central|Phan Thiet         |3749           |1848        |
|Central|Phan Rang-Thap Cham|3734           |1845        |
|Central|Hue                |3719           |1819        |
+-------+-------------------+---------------+------------+
only showing top 20 rows

     region                 city  total_customers  female_count
0      East              Cam Pha             4398          2170
1      East          Thai Nguyen             4347          2171
2      East               Phu Ly             4243          2138
3      East                Hanoi             4240          2100
4      East              Ha Long             4236          2031
5      East             Bac Ninh             4172          2017
6      East            Hai Phong             4170          2029
7      East             Nam Dinh             4169          2064
8      East            Bac Giang             4160          2014
9      East            Ninh Binh             4081          2011
10     East              Son Tay             4075          2017
11     East             Viet Tri             4054          1941
12     East              Uong Bi             4026          1959
13  Central             Dong Hoi             3912          1877
14  Central              Kon Tum             3838          1794
15     East              Lao Cai             3807          1811
16  Central               Hoi An             3760          1833
17  Central           Phan Thiet             3749          1848
18  Central  Phan Rang-Thap Cham             3734          1845
19  Central                  Hue             3719          1819
20  Central              Tuy Hoa             3674          1837
21  Central              Da Nang             3616          1755
22  Central           Quang Ngai             3616          1778
23  Central               Tam Ky             3562          1772
24  Central             Quy Nhon             3556          1744
25  Central            Nha Trang             3550          1636
26     West     Ho Chi Minh City             1359           683
27     West            Vinh Long             1336           627
28     West               Pleiku             1253           605
29     West             Vung Tau             1251           610
30     West               Da Lat             1243           607
31     West              Can Tho             1214           587
32     West             Bac Lieu             1211           599
33     West               Ca Mau             1211           605
34     West            Soc Trang             1208           604
35     West               My Tho             1198           599
36     West           Long Xuyen             1194           586
37     West              Ben Tre             1179           599
38     West             Bien Hoa             1173           588
39     West        Buon Ma Thuot             1167           626
40     West             Tra Vinh             1138           548
41     West             Rach Gia             1131           556

Q6.Xếp hạng sản phẩm trong từng category (products JOIN reviews)

In [19]:
result_q6 = spark.sql("""
SELECT product_name, category,
       ROUND(AVG(rating), 2) AS avg_rating,
       COUNT(*) AS review_count,
       RANK() OVER (PARTITION BY category ORDER BY AVG(rating) DESC) AS rank_in_category,
       DENSE_RANK() OVER (ORDER BY AVG(rating) DESC) AS overall_rank
FROM reviews r
JOIN products p ON r.product_id = p.product_id
GROUP BY product_name, category;""")
result_q6.show(truncate=False)
result_q6.toPandas()

26/06/13 19:14:41 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
26/06/13 19:14:41 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
26/06/13 19:14:42 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
26/06/13 19:14:42 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
26/06/13 19:14:42 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
26/06/13 19:14:42 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
26/06/13 19:14:42 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
26/06/13 19:14:42 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
26/06/13 19:14:42 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
26/06/13 19:14:42 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
26/06/13 19:14:42 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
26/06/13 19:14:42 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.

+-----------------+--------+----------+------------+----------------+------------+
|product_name     |category|avg_rating|review_count|rank_in_category|overall_rank|
+-----------------+--------+----------+------------+----------------+------------+
|DragonWear MA-40 |Casual  |5.0       |2           |1               |1           |
|DragonWear MA-10 |Casual  |5.0       |3           |1               |1           |
|VietMode MA-21   |Casual  |5.0       |1           |1               |1           |
|DragonWear MA-12 |Casual  |5.0       |1           |1               |1           |
|VietMode MA-24   |Casual  |5.0       |1           |1               |1           |
|VietMode MP-17   |Casual  |5.0       |1           |1               |1           |
|SaigonCore MA-04 |Casual  |5.0       |1           |1               |1           |
|DragonWear MA-23 |Casual  |4.75      |4           |8               |3           |
|VietMode MA-07   |Casual  |4.75      |4           |8               |3           |
|MekongFit MA-02  |Casual  |4.64      |22          |10              |6           |
|VietMode MA-25   |Casual  |4.6       |5           |11              |7           |
|VietMode MP-27   |Casual  |4.5       |12          |12              |12          |
|PhoenixWear MA-05|Casual  |4.5       |2           |12              |12          |
|SaigonCore MA-05 |Casual  |4.5       |2           |12              |12          |
|VietMode MP-31   |Casual  |4.4       |5           |15              |16          |
|VietMode MP-13   |Casual  |4.4       |15          |15              |16          |
|HanoiStreet MA-18|Casual  |4.39      |23          |17              |17          |
|DragonWear MA-13 |Casual  |4.33      |6           |18              |22          |
|VietMode MA-22   |Casual  |4.18      |28          |19              |47          |
|DragonWear MA-03 |Casual  |4.15      |99          |20              |56          |
+-----------------+--------+----------+------------+----------------+------------+
only showing top 20 rows

26/06/13 19:14:42 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
26/06/13 19:14:42 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
26/06/13 19:14:42 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
26/06/13 19:14:42 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.

,product_name,category,avg_rating,review_count,rank_in_category,overall_rank
0,DragonWear MA-40,Casual,5.00,2,1,1
1,DragonWear MA-10,Casual,5.00,3,1,1
2,VietMode MA-21,Casual,5.00,1,1,1
3,DragonWear MA-12,Casual,5.00,1,1,1
4,VietMode MA-24,Casual,5.00,1,1,1
...,...,...,...,...,...,...
1274,NamStyle UE-01,Streetwear,2.00,1,725,603
1275,MekongFit UE-31,Streetwear,2.00,1,725,603
1276,VietMode UE-13,Streetwear,2.00,1,725,603
1277,SaigonCore UC-02,Streetwear,1.67,3,732,604
1278,LotusWear UE-44,Streetwear,1.00,1,733,605

Q7. Phân khúc khách hàng theo 3 chỉ số quan trọng (Recency–Frequency–Monetary)

In [21]:
result_q7 = spark.sql("""
WITH frequency AS (
  SELECT customer_id, COUNT(order_id) AS order_count,
         MAX(review_date) AS last_order_date,
         DATEDIFF(CURRENT_DATE(), MAX(review_date)) AS recency_days
  FROM reviews
  GROUP BY customer_id
),
rfm AS (
  SELECT f.*, c.age_group, c.acquisition_channel,
         NTILE(4) OVER (ORDER BY recency_days ASC)    AS R_score,
         NTILE(4) OVER (ORDER BY order_count DESC)    AS F_score
  FROM frequency f
  JOIN customers c ON f.customer_id = c.customer_id
)
SELECT age_group, acquisition_channel,
       ROUND(AVG(R_score + F_score), 2) AS avg_rfm_score,
       COUNT(*) AS customer_count
FROM rfm
GROUP BY age_group, acquisition_channel
ORDER BY avg_rfm_score DESC
""")

result_q7.show(truncate=False)
result_q7.toPandas()

26/06/13 19:15:58 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
26/06/13 19:15:58 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
26/06/13 19:15:58 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
26/06/13 19:15:58 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
26/06/13 19:15:58 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
26/06/13 19:15:58 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
26/06/13 19:15:58 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
26/06/13 19:15:58 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
26/06/13 19:15:58 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
26/06/13 19:15:58 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
26/06/13 19:15:58 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
26/06/13 19:15:58 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
26/06/13 19:15:58 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
26/06/13 19:15:58 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
26/06/13 19:15:58 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
26/06/13 19:15:58 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
26/06/13 19:15:58 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
26/06/13 19:15:58 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
26/06/13 19:15:58 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
26/06/13 19:15:58 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.

+---------+-------------------+-------------+--------------+
|age_group|acquisition_channel|avg_rfm_score|customer_count|
+---------+-------------------+-------------+--------------+
|18-24    |direct             |5.19         |545           |
|45-54    |referral           |5.07         |920           |
|35-44    |referral           |5.07         |1246          |
|35-44    |email_campaign     |5.07         |1567          |
|55+      |organic_search     |5.05         |1637          |
|55+      |social_media       |5.05         |1108          |
|45-54    |direct             |5.04         |757           |
|25-34    |social_media       |5.03         |2848          |
|55+      |paid_search        |5.03         |1088          |
|55+      |email_campaign     |5.03         |639           |
|55+      |direct             |5.03         |447           |
|25-34    |organic_search     |5.02         |4319          |
|45-54    |organic_search     |5.02         |2807          |
|55+      |referral           |5.02         |546           |
|25-34    |paid_search        |5.01         |2876          |
|35-44    |social_media       |5.01         |2590          |
|18-24    |paid_search        |5.01         |1393          |
|18-24    |social_media       |5.01         |1402          |
|18-24    |referral           |5.01         |666           |
|25-34    |email_campaign     |5.01         |1712          |
+---------+-------------------+-------------+--------------+
only showing top 20 rows

26/06/13 19:15:59 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
26/06/13 19:15:59 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
26/06/13 19:15:59 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
26/06/13 19:15:59 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
26/06/13 19:15:59 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
26/06/13 19:15:59 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
26/06/13 19:15:59 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
26/06/13 19:15:59 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
26/06/13 19:15:59 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
26/06/13 19:15:59 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
26/06/13 19:15:59 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
26/06/13 19:15:59 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.

   age_group acquisition_channel  avg_rfm_score  customer_count
0      18-24              direct           5.19             545
1      45-54            referral           5.07             920
2      35-44            referral           5.07            1246
3      35-44      email_campaign           5.07            1567
4        55+      organic_search           5.05            1637
5        55+        social_media           5.05            1108
6      45-54              direct           5.04             757
7      25-34        social_media           5.03            2848
8        55+         paid_search           5.03            1088
9        55+      email_campaign           5.03             639
10       55+              direct           5.03             447
11     25-34      organic_search           5.02            4319
12     45-54      organic_search           5.02            2807
13       55+            referral           5.02             546
14     25-34         paid_search           5.01            2876
15     35-44        social_media           5.01            2590
16     18-24         paid_search           5.01            1393
17     18-24        social_media           5.01            1402
18     18-24            referral           5.01             666
19     25-34      email_campaign           5.01            1712
20     35-44              direct           5.00            1033
21     45-54        social_media           4.99            1841
22     18-24      email_campaign           4.99             802
23     18-24      organic_search           4.98            1974
24     25-34            referral           4.95            1440
25     35-44         paid_search           4.95            2552
26     45-54      email_campaign           4.94            1110
27     35-44      organic_search           4.94            3773
28     45-54         paid_search           4.92            1848
29     25-34              direct           4.86            1190

Q8.Đánh giá sản phẩm theo vùng

In [22]:
result_q8 = spark.sql("""
WITH traffic_monthly AS (
  SELECT DATE_FORMAT(date, 'yyyy-MM') AS month,
         traffic_source, SUM(sessions) AS sessions
  FROM web_traffic GROUP BY month, traffic_source
),
region_revenue AS (
  SELECT DATE_FORMAT(s.Date, 'yyyy-MM') AS month,
         g.region, SUM(s.Revenue) AS revenue, SUM(s.COGS) AS cogs
  FROM sales s
  JOIN customers c ON DATE_FORMAT(s.Date,'yyyy-MM') = DATE_FORMAT(c.signup_date,'yyyy-MM')
  JOIN geography g ON c.zip = g.zip
  GROUP BY month, g.region
)
SELECT t.month, t.traffic_source, t.sessions,
       r.region, ROUND(r.revenue, 2) AS revenue,
       ROUND(r.revenue / NULLIF(t.sessions, 0), 2) AS revenue_per_session
FROM traffic_monthly t
JOIN region_revenue r ON t.month = r.month
ORDER BY t.month, revenue_per_session DESC;
                   """)

result_q8.show(truncate=False)
result_q8.toPandas()

+-------+--------------+--------+-------+---------------+-------------------+
|month  |traffic_source|sessions|region |revenue        |revenue_per_session|
+-------+--------------+--------+-------+---------------+-------------------+
|2013-01|referral      |28134   |East   |8.30908960973E9|295339.79          |
|2013-01|social_media  |28776   |East   |8.30908960973E9|288750.68          |
|2013-01|direct        |37852   |East   |8.30908960973E9|219515.21          |
|2013-01|referral      |28134   |Central|5.20459459071E9|184993.05          |
|2013-01|social_media  |28776   |Central|5.20459459071E9|180865.81          |
|2013-01|email_campaign|49649   |East   |8.30908960973E9|167356.64          |
|2013-01|direct        |37852   |Central|5.20459459071E9|137498.54          |
|2013-01|paid_search   |72457   |East   |8.30908960973E9|114676.15          |
|2013-01|organic_search|78138   |East   |8.30908960973E9|106338.65          |
|2013-01|email_campaign|49649   |Central|5.20459459071E9|104827.78          |
|2013-01|referral      |28134   |West   |2.64795163387E9|94119.27           |
|2013-01|social_media  |28776   |West   |2.64795163387E9|92019.45           |
|2013-01|paid_search   |72457   |Central|5.20459459071E9|71830.11           |
|2013-01|direct        |37852   |West   |2.64795163387E9|69955.4            |
|2013-01|organic_search|78138   |Central|5.20459459071E9|66607.73           |
|2013-01|email_campaign|49649   |West   |2.64795163387E9|53333.43           |
|2013-01|paid_search   |72457   |West   |2.64795163387E9|36545.15           |
|2013-01|organic_search|78138   |West   |2.64795163387E9|33888.14           |
|2013-02|referral      |14103   |East   |9.55113300078E9|677241.23          |
|2013-02|referral      |14103   |Central|6.25763886258E9|443709.77          |
+-------+--------------+--------+-------+---------------+-------------------+
only showing top 20 rows

,month,traffic_source,sessions,region,revenue,revenue_per_session
0,2013-01,referral,28134,East,8.309090e+09,295339.79
1,2013-01,social_media,28776,East,8.309090e+09,288750.68
2,2013-01,direct,37852,East,8.309090e+09,219515.21
3,2013-01,referral,28134,Central,5.204595e+09,184993.05
4,2013-01,social_media,28776,Central,5.204595e+09,180865.81
...,...,...,...,...,...,...
2083,2022-12,paid_search,102170,West,1.641840e+10,160696.83
2084,2022-12,organic_search,221159,Central,3.462026e+10,156540.13
2085,2022-12,email_campaign,106602,West,1.641840e+10,154015.83
2086,2022-12,social_media,127109,West,1.641840e+10,129167.84
2087,2022-12,organic_search,221159,West,1.641840e+10,74237.97

Q9.Phân tích tồn kho toàn diện theo category & segment

In [23]:
result_q9 = spark.sql("""
WITH monthly_inventory AS (
    SELECT
        year, month, category, segment,
        SUM(stock_on_hand)                                  AS total_stock,
        SUM(units_received)                                 AS total_received,
        SUM(units_sold)                                     AS total_sold,
        SUM(stockout_days)                                  AS total_stockout_days,
        ROUND(AVG(days_of_supply), 1)                       AS avg_days_of_supply,
        ROUND(AVG(fill_rate) * 100, 2)                      AS avg_fill_rate_pct,
        ROUND(AVG(sell_through_rate) * 100, 2)              AS avg_sell_through_pct,
        SUM(stockout_flag)                                  AS stockout_products,
        SUM(overstock_flag)                                 AS overstock_products,
        SUM(reorder_flag)                                   AS need_reorder_products,
        COUNT(DISTINCT product_id)                          AS total_products
    FROM inventory
    GROUP BY year, month, category, segment
),
with_status_ratio AS (
    SELECT *,
        ROUND(stockout_products  * 100.0 / total_products, 2) AS stockout_rate_pct,
        ROUND(overstock_products * 100.0 / total_products, 2) AS overstock_rate_pct,
        ROUND(total_sold * 100.0 / NULLIF(total_received + total_stock, 0), 2) AS inventory_turnover_pct,
        RANK() OVER (
            PARTITION BY year, month
            ORDER BY avg_fill_rate_pct DESC
        )                                                   AS fill_rate_rank
    FROM monthly_inventory
)
SELECT
    year, month, category, segment,
    total_stock,
    total_sold,
    avg_days_of_supply,
    avg_fill_rate_pct,
    avg_sell_through_pct,
    stockout_rate_pct,
    overstock_rate_pct,
    inventory_turnover_pct,
    need_reorder_products,
    fill_rate_rank,
    CASE
        WHEN avg_sell_through_pct >= 80 AND stockout_rate_pct < 10  THEN 'Healthy'
        WHEN stockout_rate_pct >= 30                                 THEN 'Critical Stockout'
        WHEN overstock_rate_pct >= 40                                THEN 'Overstock Risk'
        WHEN need_reorder_products > total_products * 0.5           THEN 'Reorder Urgent'
        ELSE                                                              'Monitor'
    END                                                         AS inventory_health
FROM with_status_ratio
ORDER BY year, month, stockout_rate_pct DESC
""")

result_q9.show(30, truncate=False)
result_q9.toPandas()

+----+-----+----------+-----------+-----------+----------+------------------+-----------------+--------------------+-----------------+------------------+----------------------+---------------------+--------------+-----------------+
|year|month|category  |segment    |total_stock|total_sold|avg_days_of_supply|avg_fill_rate_pct|avg_sell_through_pct|stockout_rate_pct|overstock_rate_pct|inventory_turnover_pct|need_reorder_products|fill_rate_rank|inventory_health |
+----+-----+----------+-----------+-----------+----------+------------------+-----------------+--------------------+-----------------+------------------+----------------------+---------------------+--------------+-----------------+
|2012|7    |GenZ      |Trendy     |1314       |416       |94.7              |95.78            |24.06               |80.00            |86.67             |23.16                 |0                    |8             |Critical Stockout|
|2012|7    |Streetwear|Performance|2928       |922       |93.0              |96.32            |24.42               |75.44            |54.39             |22.98                 |0                    |6             |Critical Stockout|
|2012|7    |Casual    |All-weather|497        |158       |92.9              |96.04            |24.43               |75.00            |56.25             |23.30                 |0                    |7             |Critical Stockout|
|2012|7    |Streetwear|Everyday   |7675       |2401      |94.5              |96.43            |24.11               |71.76            |78.82             |22.76                 |0                    |5             |Critical Stockout|
|2012|7    |Streetwear|Balanced   |2589       |816       |92.4              |96.52            |24.53               |64.44            |44.44             |23.01                 |0                    |4             |Critical Stockout|
|2012|7    |Streetwear|Standard   |498        |161       |91.3              |97.29            |24.73               |62.50            |28.13             |23.89                 |0                    |1             |Critical Stockout|
|2012|7    |Outdoor   |Activewear |7764       |2438      |93.3              |96.87            |24.35               |60.77            |57.69             |22.89                 |0                    |2             |Critical Stockout|
|2012|7    |Outdoor   |Premium    |433        |139       |92.8              |96.67            |24.44               |53.33            |73.33             |23.64                 |0                    |3             |Critical Stockout|
|2012|8    |Streetwear|Standard   |514        |202       |131.5             |95.68            |31.39               |81.48            |33.33             |27.26                 |0                    |5             |Critical Stockout|
|2012|8    |Streetwear|Balanced   |2941       |1076      |119.3             |88.27            |31.4                |81.48            |29.63             |25.50                 |0                    |8             |Critical Stockout|
|2012|8    |Streetwear|Everyday   |8536       |2836      |89.2              |93.65            |29.43               |74.74            |45.26             |23.87                 |0                    |6             |Critical Stockout|
|2012|8    |Outdoor   |Premium    |585        |367       |71.1              |91.05            |34.1                |73.68            |26.32             |35.87                 |0                    |7             |Critical Stockout|
|2012|8    |GenZ      |Trendy     |1463       |490       |109.8             |96.83            |23.41               |70.00            |45.00             |23.96                 |0                    |3             |Critical Stockout|
|2012|8    |Outdoor   |Activewear |8530       |3660      |91.1              |95.96            |28.62               |68.94            |25.76             |28.42                 |0                    |4             |Critical Stockout|
|2012|8    |Streetwear|Performance|3146       |1167      |105.6             |97.18            |25.94               |59.32            |37.29             |25.89                 |0                    |2             |Critical Stockout|
|2012|8    |Casual    |All-weather|534        |185       |104.7             |97.45            |26.72               |52.94            |35.29             |24.57                 |0                    |1             |Critical Stockout|
|2012|9    |GenZ      |Trendy     |1506       |293       |198.5             |95.61            |16.75               |84.21            |84.21             |15.88                 |0                    |4             |Critical Stockout|
|2012|9    |Outdoor   |Premium    |692        |451       |81.4              |89.37            |34.85               |76.19            |28.57             |36.70                 |0                    |8             |Critical Stockout|
|2012|9    |Streetwear|Balanced   |3077       |894       |153.4             |92.28            |27.48               |66.67            |50.00             |21.72                 |0                    |7             |Critical Stockout|
|2012|9    |Streetwear|Everyday   |8885       |1838      |170.9             |94.83            |22.92               |65.63            |70.83             |16.61                 |0                    |6             |Critical Stockout|
|2012|9    |Casual    |All-weather|561        |133       |143.3             |96.67            |21.35               |64.71            |64.71             |18.60                 |0                    |3             |Critical Stockout|
|2012|9    |Outdoor   |Activewear |9159       |2920      |124.6             |95.61            |25.65               |61.27            |47.89             |23.20                 |0                    |4             |Critical Stockout|
|2012|9    |Streetwear|Standard   |493        |123       |122.6             |97.07            |22.98               |60.00            |52.00             |19.77                 |0                    |1             |Critical Stockout|
|2012|9    |Streetwear|Performance|3146       |651       |160.9             |97.07            |20.32               |60.00            |70.00             |16.72                 |0                    |1             |Critical Stockout|
|2012|10   |Streetwear|Standard   |539        |157       |150.8             |93.57            |23.78               |82.14            |50.00             |21.87                 |0                    |6             |Critical Stockout|
|2012|10   |Streetwear|Performance|3315       |460       |255.2             |95.94            |16.49               |71.67            |76.67             |11.93                 |0                    |4             |Critical Stockout|
|2012|10   |Streetwear|Balanced   |3133       |819       |148.0             |92.86            |25.01               |65.31            |59.18             |20.03                 |0                    |7             |Critical Stockout|
|2012|10   |Streetwear|Everyday   |9174       |1630      |192.7             |95.02            |20.37               |63.92            |74.23             |14.69                 |0                    |5             |Critical Stockout|
|2012|10   |Outdoor   |Premium    |835        |413       |151.9             |90.76            |28.8                |63.64            |50.00             |31.10                 |0                    |8             |Critical Stockout|
|2012|10   |Outdoor   |Activewear |10092      |2788      |151.0             |96.37            |24.06               |63.19            |56.94             |20.92                 |0                    |3             |Critical Stockout|
+----+-----+----------+-----------+-----------+----------+------------------+-----------------+--------------------+-----------------+------------------+----------------------+---------------------+--------------+-----------------+
only showing top 30 rows

,year,month,category,segment,total_stock,total_sold,avg_days_of_supply,avg_fill_rate_pct,avg_sell_through_pct,stockout_rate_pct,overstock_rate_pct,inventory_turnover_pct,need_reorder_products,fill_rate_rank,inventory_health
0,2012,7,GenZ,Trendy,1314,416,94.7,95.78,24.06,80.00,86.67,23.16,0,8,Critical Stockout
1,2012,7,Streetwear,Performance,2928,922,93.0,96.32,24.42,75.44,54.39,22.98,0,6,Critical Stockout
2,2012,7,Casual,All-weather,497,158,92.9,96.04,24.43,75.00,56.25,23.30,0,7,Critical Stockout
3,2012,7,Streetwear,Everyday,7675,2401,94.5,96.43,24.11,71.76,78.82,22.76,0,5,Critical Stockout
4,2012,7,Streetwear,Balanced,2589,816,92.4,96.52,24.53,64.44,44.44,23.01,0,4,Critical Stockout
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1092,2022,12,Streetwear,Everyday,19466,406,3319.0,96.25,7.79,70.83,94.44,2.04,0,5,Critical Stockout
1093,2022,12,Streetwear,Balanced,9105,623,713.2,96.67,14.43,62.71,76.27,6.34,0,4,Critical Stockout
1094,2022,12,GenZ,Trendy,5126,199,1019.4,97.20,11.75,56.82,84.09,3.72,0,3,Critical Stockout
1095,2022,12,Streetwear,Standard,553,58,437.3,97.56,12.49,53.33,80.00,9.39,0,1,Critical Stockout
1096,2022,12,Outdoor,Premium,6640,301,537.5,97.38,17.12,45.24,64.29,4.31,0,2,Critical Stockout

Nhìn vào inventory_health để ưu tiên xử lý — Critical Stockout mất doanh thu ngay lập tức, Overstock Risk gây đọng vốn, Reorder Urgent cần đặt hàng nhà cung cấp sớm.

Q10.Cohort Retention: Tỷ lệ khách hàng quay lại theo năm đăng ký. Cohort năm nào có retention_rate_pct giảm mạnh sau Year 1 cần xem lại chiến lược giữ chân khách hàng. Phát hiện những ngày doanh thu bất thường (tăng đột biến hoặc giảm mạnh hơn 2 độ lệch chuẩn) — thường trùng với sự kiện khuyến mãi hoặc sự cố hệ thống.

In [24]:
result_q10 = spark.sql("""
    WITH customer_cohort AS (
        SELECT
            c.customer_id,
            YEAR(c.signup_date)                        AS cohort_year,
            YEAR(r.review_date)                        AS activity_year,
            COUNT(r.review_id)                         AS orders_in_year
        FROM customers c
        JOIN reviews r ON c.customer_id = r.customer_id
        GROUP BY c.customer_id, YEAR(c.signup_date), YEAR(r.review_date)
    ),
    cohort_size AS (
        SELECT cohort_year, COUNT(DISTINCT customer_id) AS total_customers
        FROM customer_cohort
        GROUP BY cohort_year
    ),
    cohort_activity AS (
        SELECT
            cohort_year,
            activity_year,
            (activity_year - cohort_year)              AS year_since_signup,
            COUNT(DISTINCT customer_id)                AS active_customers
        FROM customer_cohort
        GROUP BY cohort_year, activity_year
    )
    SELECT
        ca.cohort_year,
        ca.year_since_signup,
        ca.active_customers,
        cs.total_customers,
        ROUND(ca.active_customers * 100.0 / cs.total_customers, 2) AS retention_rate_pct
    FROM cohort_activity ca
    JOIN cohort_size cs ON ca.cohort_year = cs.cohort_year
    WHERE ca.year_since_signup >= 0
    ORDER BY ca.cohort_year, ca.year_since_signup
""")

result_q10.show(50)
result_q10.toPandas()

+-----------+-----------------+----------------+---------------+------------------+
|cohort_year|year_since_signup|active_customers|total_customers|retention_rate_pct|
+-----------+-----------------+----------------+---------------+------------------+
|       2012|                0|              29|            379|              7.65|
|       2012|                1|              78|            379|             20.58|
|       2012|                2|              99|            379|             26.12|
|       2012|                3|             112|            379|             29.55|
|       2012|                4|              92|            379|             24.27|
|       2012|                5|              85|            379|             22.43|
|       2012|                6|              81|            379|             21.37|
|       2012|                7|              45|            379|             11.87|
|       2012|                8|              39|            379|             10.29|
|       2012|                9|              47|            379|             12.40|
|       2012|               10|              35|            379|              9.23|
|       2013|                0|             288|           1231|             23.40|
|       2013|                1|             284|           1231|             23.07|
|       2013|                2|             314|           1231|             25.51|
|       2013|                3|             315|           1231|             25.59|
|       2013|                4|             292|           1231|             23.72|
|       2013|                5|             248|           1231|             20.15|
|       2013|                6|             162|           1231|             13.16|
|       2013|                7|             120|           1231|              9.75|
|       2013|                8|             155|           1231|             12.59|
|       2013|                9|             129|           1231|             10.48|
|       2014|                0|             492|           1987|             24.76|
|       2014|                1|             481|           1987|             24.21|
|       2014|                2|             477|           1987|             24.01|
|       2014|                3|             465|           1987|             23.40|
|       2014|                4|             474|           1987|             23.86|
|       2014|                5|             263|           1987|             13.24|
|       2014|                6|             230|           1987|             11.58|
|       2014|                7|             227|           1987|             11.42|
|       2014|                8|             212|           1987|             10.67|
|       2015|                0|             652|           2821|             23.11|
|       2015|                1|             712|           2821|             25.24|
|       2015|                2|             675|           2821|             23.93|
|       2015|                3|             635|           2821|             22.51|
|       2015|                4|             375|           2821|             13.29|
|       2015|                5|             324|           2821|             11.49|
|       2015|                6|             323|           2821|             11.45|
|       2015|                7|             308|           2821|             10.92|
|       2016|                0|             883|           3614|             24.43|
|       2016|                1|             869|           3614|             24.05|
|       2016|                2|             778|           3614|             21.53|
|       2016|                3|             464|           3614|             12.84|
|       2016|                4|             424|           3614|             11.73|
|       2016|                5|             372|           3614|             10.29|
|       2016|                6|             383|           3614|             10.60|
|       2017|                0|            1001|           4452|             22.48|
|       2017|                1|             952|           4452|             21.38|
|       2017|                2|             556|           4452|             12.49|
|       2017|                3|             580|           4452|             13.03|
|       2017|                4|             492|           4452|             11.05|
+-----------+-----------------+----------------+---------------+------------------+
only showing top 50 rows

,cohort_year,year_since_signup,active_customers,total_customers,retention_rate_pct
0,2012,0,29,379,7.65
1,2012,1,78,379,20.58
2,2012,2,99,379,26.12
3,2012,3,112,379,29.55
4,2012,4,92,379,24.27
...,...,...,...,...,...
61,2020,1,785,6910,11.36
62,2020,2,761,6910,11.01
63,2021,0,792,7568,10.47
64,2021,1,847,7568,11.19
65,2022,0,920,8411,10.94

Q11.Doanh thu trung bình động 30 ngày + phát hiện bất thường

In [25]:
result_q11 = spark.sql("""
    WITH daily_revenue AS (
        SELECT
            Date,
            Revenue,
            COGS,
            ROUND(Revenue - COGS, 2)                   AS daily_profit
        FROM sales
    ),
    moving_avg AS (
        SELECT
            Date,
            Revenue,
            daily_profit,
            ROUND(AVG(Revenue) OVER (
                ORDER BY Date
                ROWS BETWEEN 29 PRECEDING AND CURRENT ROW
            ), 2)                                      AS ma30_revenue,
            ROUND(STDDEV(Revenue) OVER (
                ORDER BY Date
                ROWS BETWEEN 29 PRECEDING AND CURRENT ROW
            ), 2)                                      AS stddev30_revenue,
            ROUND(AVG(daily_profit) OVER (
                ORDER BY Date
                ROWS BETWEEN 6 PRECEDING AND CURRENT ROW
            ), 2)                                      AS ma7_profit
        FROM daily_revenue
    )
    SELECT
        Date,
        ROUND(Revenue, 2)                              AS revenue,
        ma30_revenue,
        ma7_profit,
        ROUND(Revenue - ma30_revenue, 2)               AS deviation_from_ma30,
        CASE
            WHEN Revenue > ma30_revenue + 2 * stddev30_revenue THEN 'Spike'
            WHEN Revenue < ma30_revenue - 2 * stddev30_revenue THEN 'Drop'
            ELSE 'Normal'
        END                                            AS anomaly_flag
    FROM moving_avg
    WHERE stddev30_revenue IS NOT NULL
    ORDER BY Date
""")

result_q11.filter("anomaly_flag != 'Normal'").show(20)

+----------+-------------+------------+----------+-------------------+------------+
|      Date|      revenue|ma30_revenue|ma7_profit|deviation_from_ma30|anomaly_flag|
+----------+-------------+------------+----------+-------------------+------------+
|2012-07-31|   9151622.14|  4657384.77|1264908.52|         4494237.37|       Spike|
|2012-08-01|    9148357.3|  4812245.89| 1369647.7|         4336111.41|       Spike|
|2012-08-02|    9692427.0|  4974918.59|1495666.63|         4717508.41|       Spike|
|2012-08-03|   9297269.95|  5114042.66|1640118.66|         4183227.29|       Spike|
|2012-08-28|   9508676.62|  4879174.08|1096418.81|         4629502.54|       Spike|
|2012-08-30| 1.00865341E7|  4999485.39|1345210.26|         5087048.71|       Spike|
|2012-10-28|   6259883.83|  3448998.56| 734325.51|         2810885.27|       Spike|
|2012-10-29|    5424539.1|  3453004.05| 792504.97|         1971535.05|       Spike|
|2012-10-30|   6347274.89|  3508100.55| 856805.48|         2839174.34|       Spike|
|2012-12-02|   1765509.34|  3184768.26| 667414.02|        -1419258.92|        Drop|
|2012-12-27|   4994041.71|  3203379.17| 756176.61|         1790662.54|       Spike|
|2012-12-28|   8573663.31|  3356492.26| 913257.77|         5217171.05|       Spike|
|2012-12-29|   7842913.37|  3514054.82|1044164.36|         4328858.55|       Spike|
|2013-02-24|   5419232.89|   3581892.5| 764171.77|         1837340.39|       Spike|
|2013-02-25|   9128225.25|  3809090.32| 913804.78|         5319134.93|       Spike|
|2013-02-26|   6762535.71|  3907212.13| 944099.87|         2855323.58|       Spike|
|2013-03-02|    279813.94|  3758561.77| 843405.42|        -3478747.83|        Drop|
|2013-03-28|   8099154.93|  4414842.92|  627145.4|         3684312.01|       Spike|
|2013-03-29|   8381683.44|  4503673.52|  649303.3|         3878009.92|       Spike|
|2013-03-30|1.163699438E7|  4745987.78| 709366.94|          6891006.6|       Spike|
+----------+-------------+------------+----------+-------------------+------------+
only showing top 20 rows

26/06/13 19:17:49 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
26/06/13 19:17:49 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
26/06/13 19:17:49 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
26/06/13 19:17:49 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
26/06/13 19:17:49 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.

Q12.Multi-dimensional Funnel: Traffic → Engagement → Purchase theo kênh & vùng. Kênh nào có visitor_to_buyer_pct thấp nhưng avg_session_duration_sec cao → khách xem nhiều nhưng không mua → cần cải thiện UX hoặc pricing.

In [26]:
result_q12 = spark.sql("""
    WITH monthly_traffic AS (
        SELECT
            DATE_FORMAT(date, 'yyyy-MM')               AS month,
            traffic_source,
            SUM(sessions)                              AS sessions,
            SUM(unique_visitors)                       AS unique_visitors,
            SUM(page_views)                            AS page_views,
            ROUND(AVG(bounce_rate) * 100, 2)           AS avg_bounce_pct,
            ROUND(AVG(avg_session_duration_sec), 1)    AS avg_duration_sec
        FROM web_traffic
        GROUP BY month, traffic_source
    ),
    monthly_orders AS (
        SELECT
            DATE_FORMAT(r.review_date, 'yyyy-MM')      AS month,
            g.region,
            COUNT(DISTINCT r.order_id)                 AS total_orders,
            COUNT(DISTINCT r.customer_id)              AS unique_buyers,
            ROUND(AVG(r.rating), 2)                    AS avg_rating
        FROM reviews r
        JOIN customers c  ON r.customer_id = c.customer_id
        JOIN geography g  ON c.zip = g.zip
        GROUP BY month, g.region
    ),
    monthly_revenue AS (
        SELECT
            DATE_FORMAT(Date, 'yyyy-MM')               AS month,
            ROUND(SUM(Revenue), 2)                     AS revenue,
            ROUND(SUM(COGS), 2)                        AS cogs
        FROM sales
        GROUP BY month
    )
    SELECT
        t.month,
        t.traffic_source,
        o.region,
        t.sessions,
        t.unique_visitors,
        o.unique_buyers,
        o.total_orders,
        r.revenue,
        ROUND(o.unique_buyers * 100.0 / NULLIF(t.unique_visitors, 0), 2) AS visitor_to_buyer_pct,
        ROUND(r.revenue / NULLIF(t.sessions, 0), 2)                      AS revenue_per_session,
        ROUND(r.revenue / NULLIF(o.total_orders, 0), 2)                  AS avg_order_value,
        t.avg_bounce_pct,
        o.avg_rating
    FROM monthly_traffic t
    JOIN monthly_orders  o ON t.month = o.month
    JOIN monthly_revenue r ON t.month = r.month
    ORDER BY t.month, revenue_per_session DESC
""")

result_q12.show(20)
result_q12.toPandas()

+-------+--------------+-------+--------+---------------+-------------+------------+--------------+--------------------+-------------------+---------------+--------------+----------+
|  month|traffic_source| region|sessions|unique_visitors|unique_buyers|total_orders|       revenue|visitor_to_buyer_pct|revenue_per_session|avg_order_value|avg_bounce_pct|avg_rating|
+-------+--------------+-------+--------+---------------+-------------+------------+--------------+--------------------+-------------------+---------------+--------------+----------+
|2013-01|      referral|Central|   28134|          21470|          277|         282| 9.130867703E7|                1.29|            3245.49|      323789.63|          0.51|      3.98|
|2013-01|      referral|   East|   28134|          21470|          567|         581| 9.130867703E7|                2.64|            3245.49|      157157.79|          0.51|      3.94|
|2013-01|      referral|   West|   28134|          21470|          345|         356| 9.130867703E7|                1.61|            3245.49|      256485.05|          0.51|      3.89|
|2013-01|  social_media|Central|   28776|          21863|          277|         282| 9.130867703E7|                1.27|            3173.08|      323789.63|          0.43|      3.98|
|2013-01|  social_media|   East|   28776|          21863|          567|         581| 9.130867703E7|                2.59|            3173.08|      157157.79|          0.43|      3.94|
|2013-01|  social_media|   West|   28776|          21863|          345|         356| 9.130867703E7|                1.58|            3173.08|      256485.05|          0.43|      3.89|
|2013-01|        direct|Central|   37852|          29336|          277|         282| 9.130867703E7|                0.94|            2412.26|      323789.63|          0.46|      3.98|
|2013-01|        direct|   East|   37852|          29336|          567|         581| 9.130867703E7|                1.93|            2412.26|      157157.79|          0.46|      3.94|
|2013-01|        direct|   West|   37852|          29336|          345|         356| 9.130867703E7|                1.18|            2412.26|      256485.05|          0.46|      3.89|
|2013-01|email_campaign|Central|   49649|          38116|          277|         282| 9.130867703E7|                0.73|            1839.08|      323789.63|          0.45|      3.98|
|2013-01|email_campaign|   East|   49649|          38116|          567|         581| 9.130867703E7|                1.49|            1839.08|      157157.79|          0.45|      3.94|
|2013-01|email_campaign|   West|   49649|          38116|          345|         356| 9.130867703E7|                0.91|            1839.08|      256485.05|          0.45|      3.89|
|2013-01|   paid_search|Central|   72457|          55222|          277|         282| 9.130867703E7|                0.50|            1260.18|      323789.63|           0.4|      3.98|
|2013-01|   paid_search|   East|   72457|          55222|          567|         581| 9.130867703E7|                1.03|            1260.18|      157157.79|           0.4|      3.94|
|2013-01|   paid_search|   West|   72457|          55222|          345|         356| 9.130867703E7|                0.62|            1260.18|      256485.05|           0.4|      3.89|
|2013-01|organic_search|Central|   78138|          58920|          277|         282| 9.130867703E7|                0.47|            1168.56|      323789.63|          0.49|      3.98|
|2013-01|organic_search|   East|   78138|          58920|          567|         581| 9.130867703E7|                0.96|            1168.56|      157157.79|          0.49|      3.94|
|2013-01|organic_search|   West|   78138|          58920|          345|         356| 9.130867703E7|                0.59|            1168.56|      256485.05|          0.49|      3.89|
|2013-02|      referral|   West|   14103|          10525|          234|         239|1.0978313794E8|                2.22|            7784.38|      459343.67|          0.37|      3.88|
|2013-02|      referral|   East|   14103|          10525|          243|         250|1.0978313794E8|                2.31|            7784.38|      439132.55|          0.37|      3.93|
+-------+--------------+-------+--------+---------------+-------------+------------+--------------+--------------------+-------------------+---------------+--------------+----------+
only showing top 20 rows

,month,traffic_source,region,sessions,unique_visitors,unique_buyers,total_orders,revenue,visitor_to_buyer_pct,revenue_per_session,avg_order_value,avg_bounce_pct,avg_rating
0,2013-01,referral,Central,28134,21470,277,282,91308677.03,1.29,3245.49,323789.63,0.51,3.98
1,2013-01,referral,East,28134,21470,567,581,91308677.03,2.64,3245.49,157157.79,0.51,3.94
2,2013-01,referral,West,28134,21470,345,356,91308677.03,1.61,3245.49,256485.05,0.51,3.89
3,2013-01,social_media,Central,28776,21863,277,282,91308677.03,1.27,3173.08,323789.63,0.43,3.98
4,2013-01,social_media,East,28776,21863,567,581,91308677.03,2.59,3173.08,157157.79,0.43,3.94
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2083,2022-12,social_media,East,127109,96713,142,142,52454936.20,0.15,412.68,369400.96,0.46,3.94
2084,2022-12,social_media,West,127109,96713,74,74,52454936.20,0.08,412.68,708850.49,0.46,4.14
2085,2022-12,organic_search,Central,221159,170057,95,95,52454936.20,0.06,237.18,552157.22,0.44,3.98
2086,2022-12,organic_search,East,221159,170057,142,142,52454936.20,0.08,237.18,369400.96,0.44,3.94
2087,2022-12,organic_search,West,221159,170057,74,74,52454936.20,0.04,237.18,708850.49,0.44,4.14

Advanced Promotion ROI: Phân tích hiệu quả từng đợt khuyến mãi với discount stacking. lift_pct dương và cao = khuyến mãi hiệu quả thực sự tăng doanh thu. lift_pct âm = chạy khuyến mãi nhưng doanh thu vẫn thấp hơn ngày thường → cần xem lại thời điểm hoặc kênh chạy promo.

In [27]:

result_q14 = spark.sql("""
    WITH promo_periods AS (
        SELECT
            promo_id,
            promo_name,
            promo_type,
            promo_channel,
            discount_value,
            stackable_flag,
            min_order_value,
            start_date,
            end_date,
            DATEDIFF(end_date, start_date) + 1         AS promo_duration_days
        FROM promotions
    ),
    revenue_in_promo AS (
        SELECT
            p.promo_id,
            p.promo_name,
            p.promo_type,
            p.promo_channel,
            p.discount_value,
            p.stackable_flag,
            p.promo_duration_days,
            ROUND(SUM(s.Revenue), 2)                   AS promo_revenue,
            ROUND(SUM(s.COGS), 2)                      AS promo_cogs,
            COUNT(s.Date)                              AS active_days_with_sales,
            ROUND(AVG(s.Revenue), 2)                   AS avg_daily_revenue
        FROM promo_periods p
        JOIN sales s ON s.Date BETWEEN p.start_date AND p.end_date
        GROUP BY p.promo_id, p.promo_name, p.promo_type,
                 p.promo_channel, p.discount_value,
                 p.stackable_flag, p.promo_duration_days
    ),
    baseline AS (
        SELECT ROUND(AVG(Revenue), 2) AS baseline_daily_revenue FROM sales
    )
    SELECT
        r.promo_id,
        r.promo_name,
        r.promo_type,
        r.promo_channel,
        r.discount_value                               AS discount_pct,
        r.stackable_flag,
        r.promo_duration_days,
        r.promo_revenue,
        ROUND(r.promo_revenue - r.promo_cogs, 2)       AS promo_gross_profit,
        r.avg_daily_revenue,
        b.baseline_daily_revenue,
        ROUND(r.avg_daily_revenue - b.baseline_daily_revenue, 2)        AS daily_revenue_lift,
        ROUND((r.avg_daily_revenue / b.baseline_daily_revenue - 1) * 100, 2) AS lift_pct,
        RANK() OVER (
            PARTITION BY r.promo_type
            ORDER BY (r.avg_daily_revenue / b.baseline_daily_revenue) DESC
        )                                              AS rank_in_promo_type
    FROM revenue_in_promo r
    CROSS JOIN baseline b
    ORDER BY lift_pct DESC
""")

result_q14.show(20, truncate=False)
result_q14.toPandas()

+----------+------------------+----------+-------------+------------+--------------+-------------------+--------------+------------------+-----------------+----------------------+------------------+--------+------------------+
|promo_id  |promo_name        |promo_type|promo_channel|discount_pct|stackable_flag|promo_duration_days|promo_revenue |promo_gross_profit|avg_daily_revenue|baseline_daily_revenue|daily_revenue_lift|lift_pct|rank_in_promo_type|
+----------+------------------+----------+-------------+------------+--------------+-------------------+--------------+------------------+-----------------+----------------------+------------------+--------+------------------+
|PROMO-0021|Spring Sale 2017  |percentage|all_channels |12.0        |0             |31                 |2.2803909351E8|2.25925624E7      |7356099.79       |4286584.03            |3069515.76        |71.61   |1                 |
|PROMO-0011|Spring Sale 2015  |percentage|all_channels |12.0        |1             |31                 |2.2645382844E8|2.573414292E7     |7304962.21       |4286584.03            |3018378.18        |70.41   |2                 |
|PROMO-0017|Spring Sale 2016  |percentage|all_channels |12.0        |0             |31                 |2.2242520679E8|2.188618757E7     |7175006.67       |4286584.03            |2888422.64        |67.38   |3                 |
|PROMO-0007|Spring Sale 2014  |percentage|email        |12.0        |1             |31                 |2.1381200736E8|2.147368039E7     |6897161.53       |4286584.03            |2610577.5         |60.9    |4                 |
|PROMO-0028|Mid-Year Sale 2018|percentage|social_media |18.0        |0             |30                 |1.9358634413E8|1.025001924E7     |6452878.14       |4286584.03            |2166294.11        |50.54   |5                 |
|PROMO-0027|Spring Sale 2018  |percentage|all_channels |12.0        |0             |31                 |1.9902245079E8|2.337662084E7     |6420079.06       |4286584.03            |2133495.03        |49.77   |6                 |
|PROMO-0022|Mid-Year Sale 2017|percentage|online       |18.0        |0             |30                 |1.9178456338E8|9193083.44        |6392818.78       |4286584.03            |2106234.75        |49.14   |7                 |
|PROMO-0001|Spring Sale 2013  |percentage|email        |12.0        |1             |31                 |1.8775212621E8|2.161362286E7     |6056520.2        |4286584.03            |1769936.17        |41.29   |8                 |
|PROMO-0018|Mid-Year Sale 2016|percentage|online       |18.0        |0             |30                 |1.7996179443E8|9576850.13        |5998726.48       |4286584.03            |1712142.45        |39.94   |9                 |
|PROMO-0012|Mid-Year Sale 2015|percentage|social_media |18.0        |0             |30                 |1.7104660415E8|1.176452763E7     |5701553.47       |4286584.03            |1414969.44        |33.01   |10                |
|PROMO-0008|Mid-Year Sale 2014|percentage|social_media |18.0        |0             |30                 |1.6697288201E8|9820163.66        |5565762.73       |4286584.03            |1279178.7         |29.84   |11                |
|PROMO-0002|Mid-Year Sale 2013|percentage|online       |18.0        |0             |30                 |1.6193569743E8|7919345.76        |5397856.58       |4286584.03            |1111272.55        |25.92   |12                |
|PROMO-0019|Fall Launch 2016  |percentage|online       |10.0        |0             |33                 |1.7586678729E8|2.197981004E7     |5329296.58       |4286584.03            |1042712.55        |24.33   |13                |
|PROMO-0013|Fall Launch 2015  |percentage|email        |10.0        |1             |33                 |1.7555733746E8|1.139257905E7     |5319919.32       |4286584.03            |1033335.29        |24.11   |14                |
|PROMO-0047|Spring Sale 2022  |percentage|all_channels |12.0        |1             |31                 |1.5158319585E8|1.120285005E7     |4889780.51       |4286584.03            |603196.48         |14.07   |15                |
|PROMO-0023|Fall Launch 2017  |percentage|all_channels |10.0        |1             |34                 |1.5673600167E8|7690777.11        |4609882.4        |4286584.03            |323298.37         |7.54    |16                |
|PROMO-0037|Spring Sale 2020  |percentage|online       |12.0        |0             |31                 |1.4260070301E8|1.632410516E7     |4600022.68       |4286584.03            |313438.65         |7.31    |17                |
|PROMO-0031|Spring Sale 2019  |percentage|online       |12.0        |1             |31                 |1.4119843102E8|1.52230425E7      |4554788.1        |4286584.03            |268204.07         |6.26    |18                |
|PROMO-0009|Fall Launch 2014  |percentage|all_channels |10.0        |0             |33                 |1.4827819562E8|2.123502896E7     |4493278.66       |4286584.03            |206694.63         |4.82    |19                |
|PROMO-0003|Fall Launch 2013  |percentage|email        |10.0        |0             |34                 |1.5062649006E8|9649243.28        |4430190.88       |4286584.03            |143606.85         |3.35    |20                |
+----------+------------------+----------+-------------+------------+--------------+-------------------+--------------+------------------+-----------------+----------------------+------------------+--------+------------------+
only showing top 20 rows

,promo_id,promo_name,promo_type,promo_channel,discount_pct,stackable_flag,promo_duration_days,promo_revenue,promo_gross_profit,avg_daily_revenue,baseline_daily_revenue,daily_revenue_lift,lift_pct,rank_in_promo_type
0,PROMO-0021,Spring Sale 2017,percentage,all_channels,12.0,0,31,2.280391e+08,22592562.40,7356099.79,4286584.03,3069515.76,71.61,1
1,PROMO-0011,Spring Sale 2015,percentage,all_channels,12.0,1,31,2.264538e+08,25734142.92,7304962.21,4286584.03,3018378.18,70.41,2
2,PROMO-0017,Spring Sale 2016,percentage,all_channels,12.0,0,31,2.224252e+08,21886187.57,7175006.67,4286584.03,2888422.64,67.38,3
3,PROMO-0007,Spring Sale 2014,percentage,email,12.0,1,31,2.138120e+08,21473680.39,6897161.53,4286584.03,2610577.50,60.90,4
4,PROMO-0028,Mid-Year Sale 2018,percentage,social_media,18.0,0,30,1.935863e+08,10250019.24,6452878.14,4286584.03,2166294.11,50.54,5
5,PROMO-0027,Spring Sale 2018,percentage,all_channels,12.0,0,31,1.990225e+08,23376620.84,6420079.06,4286584.03,2133495.03,49.77,6
6,PROMO-0022,Mid-Year Sale 2017,percentage,online,18.0,0,30,1.917846e+08,9193083.44,6392818.78,4286584.03,2106234.75,49.14,7
7,PROMO-0001,Spring Sale 2013,percentage,email,12.0,1,31,1.877521e+08,21613622.86,6056520.20,4286584.03,1769936.17,41.29,8
8,PROMO-0018,Mid-Year Sale 2016,percentage,online,18.0,0,30,1.799618e+08,9576850.13,5998726.48,4286584.03,1712142.45,39.94,9
9,PROMO-0012,Mid-Year Sale 2015,percentage,social_media,18.0,0,30,1.710466e+08,11764527.63,5701553.47,4286584.03,1414969.44,33.01,10
10,PROMO-0008,Mid-Year Sale 2014,percentage,social_media,18.0,0,30,1.669729e+08,9820163.66,5565762.73,4286584.03,1279178.70,29.84,11
11,PROMO-0002,Mid-Year Sale 2013,percentage,online,18.0,0,30,1.619357e+08,7919345.76,5397856.58,4286584.03,1111272.55,25.92,12
12,PROMO-0019,Fall Launch 2016,percentage,online,10.0,0,33,1.758668e+08,21979810.04,5329296.58,4286584.03,1042712.55,24.33,13
13,PROMO-0013,Fall Launch 2015,percentage,email,10.0,1,33,1.755573e+08,11392579.05,5319919.32,4286584.03,1033335.29,24.11,14
14,PROMO-0047,Spring Sale 2022,percentage,all_channels,12.0,1,31,1.515832e+08,11202850.05,4889780.51,4286584.03,603196.48,14.07,15
15,PROMO-0023,Fall Launch 2017,percentage,all_channels,10.0,1,34,1.567360e+08,7690777.11,4609882.40,4286584.03,323298.37,7.54,16
16,PROMO-0037,Spring Sale 2020,percentage,online,12.0,0,31,1.426007e+08,16324105.16,4600022.68,4286584.03,313438.65,7.31,17
17,PROMO-0031,Spring Sale 2019,percentage,online,12.0,1,31,1.411984e+08,15223042.50,4554788.10,4286584.03,268204.07,6.26,18
18,PROMO-0009,Fall Launch 2014,percentage,all_channels,10.0,0,33,1.482782e+08,21235028.96,4493278.66,4286584.03,206694.63,4.82,19
19,PROMO-0003,Fall Launch 2013,percentage,email,10.0,0,34,1.506265e+08,9649243.28,4430190.88,4286584.03,143606.85,3.35,20
20,PROMO-0041,Spring Sale 2021,percentage,online,12.0,1,31,1.373336e+08,13330990.25,4430115.69,4286584.03,143531.66,3.35,21
21,PROMO-0029,Fall Launch 2018,percentage,email,10.0,0,33,1.433001e+08,19446391.31,4342426.77,4286584.03,55842.74,1.30,22
22,PROMO-0016,Rural Special 2015,percentage,in_store,15.0,0,31,1.338273e+08,24269675.23,4317009.15,4286584.03,30425.12,0.71,23
23,PROMO-0025,Urban Blowout 2017,fixed,online,50.0,0,35,1.477802e+08,-45473459.24,4222291.19,4286584.03,-64292.84,-1.50,1
24,PROMO-0015,Urban Blowout 2015,fixed,online,50.0,0,35,1.473402e+08,-39333489.66,4209719.63,4286584.03,-76864.40,-1.79,2
25,PROMO-0005,Urban Blowout 2013,fixed,online,50.0,0,35,1.454934e+08,-37303371.14,4156953.25,4286584.03,-129630.78,-3.02,3
26,PROMO-0026,Rural Special 2017,percentage,in_store,15.0,0,31,1.255567e+08,22283866.87,4050216.89,4286584.03,-236367.14,-5.51,24
27,PROMO-0006,Rural Special 2013,percentage,in_store,15.0,0,30,1.158557e+08,20580113.15,3861857.29,4286584.03,-424726.74,-9.91,25
28,PROMO-0032,Mid-Year Sale 2019,percentage,social_media,18.0,0,30,1.058210e+08,5510909.72,3527366.77,4286584.03,-759217.26,-17.71,26
29,PROMO-0014,Year-End Sale 2015,percentage,all_channels,20.0,1,46,1.582372e+08,1782608.70,3439938.44,4286584.03,-846645.59,-19.75,27
30,PROMO-0048,Mid-Year Sale 2022,percentage,online,18.0,0,30,1.013475e+08,1568466.96,3378248.48,4286584.03,-908335.55,-21.19,28
31,PROMO-0020,Year-End Sale 2016,percentage,all_channels,20.0,0,46,1.548220e+08,2787645.49,3365695.81,4286584.03,-920888.22,-21.48,29
32,PROMO-0042,Mid-Year Sale 2021,percentage,social_media,18.0,1,30,9.903549e+07,4500170.79,3301183.16,4286584.03,-985400.87,-22.99,30
33,PROMO-0010,Year-End Sale 2014,percentage,all_channels,20.0,0,45,1.469337e+08,3333614.87,3265192.30,4286584.03,-1021391.73,-23.83,31
34,PROMO-0038,Mid-Year Sale 2020,percentage,social_media,18.0,0,30,9.318910e+07,5255542.40,3106303.28,4286584.03,-1180280.75,-27.53,32
35,PROMO-0036,Rural Special 2019,percentage,in_store,15.0,1,31,9.480632e+07,17825622.96,3058268.26,4286584.03,-1228315.77,-28.65,33
36,PROMO-0049,Fall Launch 2022,percentage,all_channels,10.0,0,32,9.486159e+07,8830571.50,2964424.72,4286584.03,-1322159.31,-30.84,34
37,PROMO-0004,Year-End Sale 2013,percentage,all_channels,20.0,0,46,1.358756e+08,3083144.88,2953818.42,4286584.03,-1332765.61,-31.09,35
38,PROMO-0033,Fall Launch 2019,percentage,email,10.0,0,33,9.696703e+07,5922472.73,2938394.87,4286584.03,-1348189.16,-31.45,36
39,PROMO-0039,Fall Launch 2020,percentage,all_channels,10.0,0,33,9.685101e+07,11941834.40,2934879.00,4286584.03,-1351705.03,-31.53,37
40,PROMO-0024,Year-End Sale 2017,percentage,all_channels,20.0,0,46,1.327477e+08,3003830.40,2885819.68,4286584.03,-1400764.35,-32.68,38
41,PROMO-0035,Urban Blowout 2019,fixed,online,50.0,0,35,9.638139e+07,-29402597.49,2753754.08,4286584.03,-1532829.95,-35.76,4
42,PROMO-0043,Fall Launch 2021,percentage,email,10.0,0,34,8.782942e+07,1615869.69,2583218.19,4286584.03,-1703365.84,-39.74,39
43,PROMO-0045,Urban Blowout 2021,fixed,online,50.0,0,35,8.758171e+07,-29143888.67,2502334.44,4286584.03,-1784249.59,-41.62,5
44,PROMO-0046,Rural Special 2021,percentage,in_store,15.0,0,31,7.179468e+07,13569381.66,2315957.44,4286584.03,-1970626.59,-45.97,40
45,PROMO-0030,Year-End Sale 2018,percentage,all_channels,20.0,0,46,9.307447e+07,3491319.78,2023358.10,4286584.03,-2263225.93,-52.80,41
46,PROMO-0050,Year-End Sale 2022,percentage,all_channels,20.0,0,44,7.555408e+07,-985721.28,1717138.19,4286584.03,-2569445.84,-59.94,42
47,PROMO-0044,Year-End Sale 2021,percentage,all_channels,20.0,1,46,7.657820e+07,-1127183.50,1664743.50,4286584.03,-2621840.53,-61.16,43
48,PROMO-0034,Year-End Sale 2019,percentage,all_channels,20.0,0,46,7.236374e+07,1350478.31,1573124.69,4286584.03,-2713459.34,-63.30,44
49,PROMO-0040,Year-End Sale 2020,percentage,all_channels,20.0,0,45,6.451309e+07,931407.62,1433624.18,4286584.03,-2852959.85,-66.56,45

Q15.inventory + returns + orders

In [28]:
result_q15 = spark.sql("""
WITH return_rate_by_product AS (
    SELECT
        r.product_id,
        COUNT(r.return_id)                                  AS total_returns,
        SUM(r.return_quantity)                              AS returned_qty,
        ROUND(AVG(r.refund_amount), 2)                      AS avg_refund,
        -- lý do trả hàng phổ biến nhất
        FIRST(r.return_reason)                              AS top_return_reason
    FROM returns r
    GROUP BY r.product_id
),
inventory_latest AS (
    SELECT product_id, product_name, category, segment,
           stock_on_hand, sell_through_rate, stockout_flag,
           overstock_flag, reorder_flag, days_of_supply
    FROM inventory
    WHERE snapshot_date = (SELECT MAX(snapshot_date) FROM inventory)
)
SELECT
    i.category, i.segment,
    i.product_name,
    i.stock_on_hand,
    ROUND(i.sell_through_rate * 100, 2)                     AS sell_through_pct,
    i.days_of_supply,
    COALESCE(r.total_returns, 0)                            AS total_returns,
    COALESCE(r.returned_qty, 0)                             AS returned_qty,
    COALESCE(r.avg_refund, 0)                               AS avg_refund,
    r.top_return_reason,
    CASE WHEN i.stockout_flag  = 1 THEN 'YES' ELSE 'NO' END AS is_stockout,
    CASE WHEN i.overstock_flag = 1 THEN 'YES' ELSE 'NO' END AS is_overstock,
    CASE WHEN i.reorder_flag   = 1 THEN 'YES' ELSE 'NO' END AS needs_reorder
FROM inventory_latest i
LEFT JOIN return_rate_by_product r ON i.product_id = r.product_id
ORDER BY total_returns DESC, stock_on_hand ASC
""")

result_q15.show(20, truncate=False)
result_q15.toPandas()

+----------+-----------+-----------------+-------------+----------------+--------------+-------------+------------+----------+-----------------+-----------+------------+-------------+
|category  |segment    |product_name     |stock_on_hand|sell_through_pct|days_of_supply|total_returns|returned_qty|avg_refund|top_return_reason|is_stockout|is_overstock|needs_reorder|
+----------+-----------+-----------------+-------------+----------------+--------------+-------------+------------+----------+-----------------+-----------+------------+-------------+
|Outdoor   |Activewear |HanoiStreet RP-80|2617         |4.84            |590.3         |619          |1732        |1936.65   |wrong_size       |YES        |YES         |NO           |
|Outdoor   |Activewear |HanoiStreet RP-79|2673         |4.74            |602.9         |582          |1577        |1846.36   |defective        |YES        |YES         |NO           |
|Streetwear|Everyday   |SaigonFlex UC-69 |2370         |0.13            |23700.0       |441          |1169        |13862.76  |wrong_size       |YES        |YES         |NO           |
|Streetwear|Performance|VietMotion UE-06 |1939         |0.97            |3061.6        |402          |1139        |14148.04  |wrong_size       |YES        |YES         |NO           |
|Streetwear|Performance|MekongFit UE-18  |1913         |0.36            |8198.6        |401          |1079        |5132.3    |defective        |YES        |YES         |NO           |
|Streetwear|Performance|HanoiStreet UE-36|1897         |0.16            |18970.0       |397          |1121        |13889.87  |defective        |YES        |YES         |NO           |
|Streetwear|Balanced   |HanoiStreet UM-10|1960         |1.11            |2672.7        |360          |996         |30220.72  |wrong_size       |NO         |YES         |NO           |
|Streetwear|Performance|VietMotion UE-05 |1489         |0.67            |4467.0        |340          |935         |17259.53  |late_delivery    |YES        |YES         |NO           |
|Streetwear|Performance|UrbanVN UE-14    |1600         |0.56            |5333.3        |313          |880         |16972.46  |changed_mind     |YES        |YES         |NO           |
|Streetwear|Everyday   |HanoiStreet UC-56|1394         |0.36            |8364.0        |290          |778         |9877.31   |late_delivery    |NO         |YES         |NO           |
|Outdoor   |Activewear |HanoiStreet RP-48|1340         |0.45            |6700.0        |289          |800         |4433.23   |wrong_size       |NO         |YES         |NO           |
|Streetwear|Performance|UrbanVN UE-15    |1256         |0.24            |12560.0       |286          |754         |16271.04  |changed_mind     |YES        |YES         |NO           |
|Outdoor   |Activewear |HanoiStreet RP-22|1402         |0.21            |14020.0       |283          |823         |11090.03  |wrong_size       |YES        |YES         |NO           |
|Streetwear|Performance|UrbanVN UE-24    |1334         |0.74            |4002.0        |277          |783         |15561.81  |changed_mind     |NO         |YES         |NO           |
|Outdoor   |Activewear |HanoiStreet RP-21|1346         |0.22            |13460.0       |275          |763         |10513.48  |defective        |NO         |YES         |NO           |
|Outdoor   |Activewear |HanoiStreet RP-47|1313         |0.45            |6565.0        |274          |778         |4577.01   |wrong_size       |NO         |YES         |NO           |
|Outdoor   |Activewear |MekongFit RP-31  |1390         |4.27            |672.6         |266          |708         |2594.12   |changed_mind     |YES        |YES         |NO           |
|Outdoor   |Activewear |MekongFit RP-32  |1373         |4.32            |664.4         |262          |729         |2738.12   |wrong_size       |NO         |YES         |NO           |
|Streetwear|Performance|HanoiStreet UE-16|1146         |0.35            |8595.0        |252          |686         |17220.3   |defective        |NO         |YES         |NO           |
|Outdoor   |Activewear |HanoiStreet RP-82|1169         |2.58            |1131.3        |248          |695         |2386.78   |defective        |YES        |YES         |NO           |
+----------+-----------+-----------------+-------------+----------------+--------------+-------------+------------+----------+-----------------+-----------+------------+-------------+
only showing top 20 rows

,category,segment,product_name,stock_on_hand,sell_through_pct,days_of_supply,total_returns,returned_qty,avg_refund,top_return_reason,is_stockout,is_overstock,needs_reorder
0,Outdoor,Activewear,HanoiStreet RP-80,2617,4.84,590.3,619,1732,1936.65,wrong_size,YES,YES,NO
1,Outdoor,Activewear,HanoiStreet RP-79,2673,4.74,602.9,582,1577,1846.36,defective,YES,YES,NO
2,Streetwear,Everyday,SaigonFlex UC-69,2370,0.13,23700.0,441,1169,13862.76,wrong_size,YES,YES,NO
3,Streetwear,Performance,VietMotion UE-06,1939,0.97,3061.6,402,1139,14148.04,wrong_size,YES,YES,NO
4,Streetwear,Performance,MekongFit UE-18,1913,0.36,8198.6,401,1079,5132.30,defective,YES,YES,NO
...,...,...,...,...,...,...,...,...,...,...,...,...,...
419,Streetwear,Performance,UrbanVN UE-02,15,6.25,450.0,0,0,0.00,None,YES,YES,NO
420,Outdoor,Premium,VietMode RS-39,16,30.43,68.6,0,0,0.00,None,YES,NO,NO
421,Streetwear,Balanced,SaigonFlex UM-57,22,50.00,30.0,0,0,0.00,None,YES,NO,NO
422,Streetwear,Everyday,BambooCraft UC-15,27,3.57,810.0,0,0,0.00,None,NO,YES,NO
423,Streetwear,Balanced,SaigonFlex UM-49,30,28.57,75.0,0,0,0.00,None,NO,NO,NO

Q16.Thời gian giao hàng trung bình theo vùng & order_source

In [9]:
result_q16 = spark.sql("""
WITH delivery_time AS (
    SELECT
        o.order_id,
        o.order_source,
        o.device_type,
        o.order_status,
        g.region,
        DATEDIFF(s.delivery_date, s.ship_date)      AS shipping_days,
        DATEDIFF(s.ship_date,     o.order_date)     AS processing_days,
        DATEDIFF(s.delivery_date, o.order_date)     AS total_fulfillment_days,
        s.shipping_fee
    FROM orders o
    JOIN shipments  s ON o.order_id  = s.order_id
    JOIN geography  g ON o.zip       = g.zip
    WHERE o.order_status = 'delivered'
)
SELECT
    region,
    order_source,
    COUNT(*)                                        AS total_orders,
    ROUND(AVG(processing_days), 1)                  AS avg_processing_days,
    ROUND(AVG(shipping_days), 1)                    AS avg_shipping_days,
    ROUND(AVG(total_fulfillment_days), 1)           AS avg_total_days,
    ROUND(AVG(shipping_fee), 2)                     AS avg_shipping_fee,
    SUM(CASE WHEN total_fulfillment_days <= 3
             THEN 1 ELSE 0 END)                     AS fast_delivery_count,
    ROUND(SUM(CASE WHEN total_fulfillment_days <= 3
             THEN 1 ELSE 0 END) * 100.0
             / COUNT(*), 2)                         AS fast_delivery_pct
FROM delivery_time
GROUP BY region, order_source
ORDER BY avg_total_days ASC
""")
result_q16.show()
result_q16.toPandas()

+-------+--------------+------------+-------------------+-----------------+--------------+----------------+-------------------+-----------------+
| region|  order_source|total_orders|avg_processing_days|avg_shipping_days|avg_total_days|avg_shipping_fee|fast_delivery_count|fast_delivery_pct|
+-------+--------------+------------+-------------------+-----------------+--------------+----------------+-------------------+-----------------+
|Central|organic_search|       41279|                1.5|              4.5|           6.0|            4.75|               5169|            12.52|
|   East|email_campaign|       28010|                1.5|              4.5|           6.0|            4.94|               3512|            12.54|
|   West|      referral|       13420|                1.5|              4.5|           6.0|            5.33|               1732|            12.91|
|Central|   paid_search|       32258|                1.5|              4.5|           6.0|            4.74|               4096|            12.70|
|   East|   paid_search|       51548|                1.5|              4.5|           6.0|            4.82|               6417|            12.45|
|   East|      referral|       23404|                1.5|              4.5|           6.0|            4.77|               3001|            12.82|
|Central|        direct|       11587|                1.5|              4.5|           6.0|            4.87|               1375|            11.87|
|   West|email_campaign|       16066|                1.5|              4.5|           6.0|            5.34|               2026|            12.61|
|Central|  social_media|       29543|                1.5|              4.5|           6.0|            4.79|               3640|            12.32|
|   East|        direct|       19018|                1.5|              4.5|           6.0|             4.9|               2355|            12.38|
|   West|        direct|       10732|                1.5|              4.5|           6.0|             5.4|               1344|            12.52|
|   West|   paid_search|       29230|                1.5|              4.5|           6.0|            5.37|               3559|            12.18|
|   East|  social_media|       47290|                1.5|              4.5|           6.0|            4.79|               5972|            12.63|
|   West|organic_search|       37584|                1.5|              4.5|           6.0|            5.46|               4653|            12.38|
|Central|email_campaign|       17815|                1.5|              4.5|           6.0|            4.84|               2234|            12.54|
|   West|  social_media|       26841|                1.5|              4.5|           6.0|            5.37|               3408|            12.70|
|   East|organic_search|       65851|                1.5|              4.5|           6.0|             4.8|               8219|            12.48|
|Central|      referral|       14716|                1.5|              4.5|           6.0|            4.89|               1798|            12.22|
+-------+--------------+------------+-------------------+-----------------+--------------+----------------+-------------------+-----------------+

,region,order_source,total_orders,avg_processing_days,avg_shipping_days,avg_total_days,avg_shipping_fee,fast_delivery_count,fast_delivery_pct
0,Central,organic_search,41279,1.5,4.5,6.0,4.75,5169,12.52
1,East,email_campaign,28010,1.5,4.5,6.0,4.94,3512,12.54
2,West,referral,13420,1.5,4.5,6.0,5.33,1732,12.91
3,Central,paid_search,32258,1.5,4.5,6.0,4.74,4096,12.70
4,East,paid_search,51548,1.5,4.5,6.0,4.82,6417,12.45
5,East,referral,23404,1.5,4.5,6.0,4.77,3001,12.82
6,Central,direct,11587,1.5,4.5,6.0,4.87,1375,11.87
7,West,email_campaign,16066,1.5,4.5,6.0,5.34,2026,12.61
8,Central,social_media,29543,1.5,4.5,6.0,4.79,3640,12.32
9,East,direct,19018,1.5,4.5,6.0,4.90,2355,12.38
10,West,direct,10732,1.5,4.5,6.0,5.40,1344,12.52
11,West,paid_search,29230,1.5,4.5,6.0,5.37,3559,12.18
12,East,social_media,47290,1.5,4.5,6.0,4.79,5972,12.63
13,West,organic_search,37584,1.5,4.5,6.0,5.46,4653,12.38
14,Central,email_campaign,17815,1.5,4.5,6.0,4.84,2234,12.54
15,West,social_media,26841,1.5,4.5,6.0,5.37,3408,12.70
16,East,organic_search,65851,1.5,4.5,6.0,4.80,8219,12.48
17,Central,referral,14716,1.5,4.5,6.0,4.89,1798,12.22

Q17. Return Analysis: Tỷ lệ hoàn trả theo lý do, danh mục & phương thức thanh toán

In [29]:
result_q17 = spark.sql("""
WITH return_detail AS (
    SELECT
        r.return_id,
        r.return_reason,
        r.return_quantity,
        r.refund_amount,
        p.category,
        p.segment,
        o.payment_method,
        o.device_type,
        o.order_source
    FROM returns     r
    JOIN order_items oi ON r.order_id    = oi.order_id
                        AND r.product_id = oi.product_id
    JOIN products    p  ON r.product_id  = p.product_id
    JOIN orders      o  ON r.order_id    = o.order_id
),
order_totals AS (
    SELECT category, COUNT(DISTINCT o.order_id) AS total_orders
    FROM orders o
    JOIN order_items oi ON o.order_id   = oi.order_id
    JOIN products    p  ON oi.product_id = p.product_id
    GROUP BY category
)
SELECT
    rd.category,
    rd.return_reason,
    rd.payment_method,
    COUNT(*)                                        AS return_count,
    SUM(rd.return_quantity)                         AS total_returned_qty,
    ROUND(SUM(rd.refund_amount), 2)                 AS total_refund,
    ROUND(AVG(rd.refund_amount), 2)                 AS avg_refund_per_return,
    ROUND(COUNT(*) * 100.0 / ot.total_orders, 2)   AS return_rate_pct
FROM return_detail rd
JOIN order_totals  ot ON rd.category = ot.category
GROUP BY rd.category, rd.return_reason, rd.payment_method, ot.total_orders
ORDER BY return_rate_pct DESC
""")
result_q17.show()
result_q17.toPandas()

+----------+----------------+--------------+------------+------------------+-------------+---------------------+---------------+
|  category|   return_reason|payment_method|return_count|total_returned_qty| total_refund|avg_refund_per_return|return_rate_pct|
+----------+----------------+--------------+------------+------------------+-------------+---------------------+---------------+
|   Outdoor|      wrong_size|   credit_card|        2515|              6840|1.338346669E7|              5321.46|           1.25|
|      GenZ|      wrong_size|   credit_card|         357|              1059|   2129286.88|              5964.39|           0.96|
|    Casual|      wrong_size|   credit_card|         227|               630|   2557893.86|             11268.25|           0.96|
|Streetwear|      wrong_size|   credit_card|        3709|             10149|6.849504013E7|             18467.25|           0.95|
|   Outdoor|       defective|   credit_card|        1493|              4164|   8174654.34|              5475.32|           0.74|
|   Outdoor|      wrong_size|           cod|        1253|              3360|   6429050.27|              5130.93|           0.63|
|   Outdoor|not_as_described|   credit_card|        1260|              3469|   6670427.05|              5293.99|           0.63|
|   Outdoor|    changed_mind|   credit_card|        1248|              3493|   6784745.24|              5436.49|           0.62|
|    Casual|       defective|   credit_card|         139|               378|   1543269.56|             11102.66|           0.59|
|      GenZ|       defective|   credit_card|         207|               584|   1046039.13|              5053.33|           0.56|
|Streetwear|       defective|   credit_card|        2162|              5886|4.008074176E7|             18538.73|           0.56|
|    Casual|    changed_mind|   credit_card|         124|               350|   1440407.55|             11616.19|           0.53|
|      GenZ|      wrong_size|           cod|         191|               479|    867037.06|              4539.46|           0.52|
|      GenZ|not_as_described|   credit_card|         187|               527|   1040778.26|              5565.66|           0.50|
|Streetwear|    changed_mind|   credit_card|        1933|              5318|3.636406878E7|             18812.24|           0.50|
|Streetwear|not_as_described|   credit_card|        1900|              5262|3.568473714E7|             18781.44|           0.49|
|Streetwear|      wrong_size|           cod|        1846|              4987|3.379179385E7|             18305.41|           0.47|
|      GenZ|    changed_mind|   credit_card|         168|               445|    809644.97|              4819.32|           0.45|
|    Casual|not_as_described|   credit_card|         105|               259|    957537.99|              9119.41|           0.44|
|    Casual|      wrong_size|           cod|          97|               267|   1056125.58|             10887.89|           0.41|
+----------+----------------+--------------+------------+------------------+-------------+---------------------+---------------+
only showing top 20 rows

,category,return_reason,payment_method,return_count,total_returned_qty,total_refund,avg_refund_per_return,return_rate_pct
0,Outdoor,wrong_size,credit_card,2515,6840,13383466.69,5321.46,1.25
1,GenZ,wrong_size,credit_card,357,1059,2129286.88,5964.39,0.96
2,Casual,wrong_size,credit_card,227,630,2557893.86,11268.25,0.96
3,Streetwear,wrong_size,credit_card,3709,10149,68495040.13,18467.25,0.95
4,Outdoor,defective,credit_card,1493,4164,8174654.34,5475.32,0.74
...,...,...,...,...,...,...,...,...
95,GenZ,late_delivery,bank_transfer,12,26,38101.81,3175.15,0.03
96,Outdoor,late_delivery,bank_transfer,68,219,451469.98,6639.26,0.03
97,Casual,late_delivery,bank_transfer,6,22,98129.82,16354.97,0.03
98,Casual,changed_mind,bank_transfer,6,10,44121.69,7353.61,0.03
99,Streetwear,late_delivery,bank_transfer,91,236,1665457.55,18301.73,0.02

Q18.Payment Intelligence: Giá trị đơn hàng & installment theo kênh và thiết bị

In [30]:
result_q18 = spark.sql("""
WITH order_value AS (
    SELECT
        o.order_id,
        o.order_source,
        o.device_type,
        o.payment_method,
        py.payment_value,
        py.installments,
        ROUND(SUM(oi.quantity * oi.unit_price), 2)          AS gross_order_value,
        ROUND(SUM(oi.discount_amount), 2)                   AS total_discount,
        ROUND(SUM(oi.quantity * oi.unit_price)
              - SUM(oi.discount_amount), 2)                 AS net_order_value,
        COUNT(DISTINCT oi.product_id)                       AS items_count
    FROM orders      o
    JOIN order_items oi ON o.order_id  = oi.order_id
    JOIN payments    py ON o.order_id  = py.order_id
    GROUP BY o.order_id, o.order_source, o.device_type,
             o.payment_method, py.payment_value, py.installments
)
SELECT
    order_source,
    device_type,
    payment_method,
    COUNT(*)                                                AS total_orders,
    ROUND(AVG(net_order_value), 2)                          AS avg_order_value,
    ROUND(AVG(items_count), 2)                              AS avg_items_per_order,
    ROUND(AVG(total_discount), 2)                           AS avg_discount,
    ROUND(AVG(installments), 2)                             AS avg_installments,
    SUM(CASE WHEN installments > 1 THEN 1 ELSE 0 END)      AS installment_orders,
    ROUND(SUM(CASE WHEN installments > 1
              THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2)    AS installment_rate_pct,
    RANK() OVER (
        PARTITION BY device_type
        ORDER BY AVG(net_order_value) DESC
    )                                                       AS rank_by_device
FROM order_value
GROUP BY order_source, device_type, payment_method
ORDER BY avg_order_value DESC
""")
result_q18.show()
result_q18.toPandas()

+--------------+-----------+--------------+------------+---------------+-------------------+------------+----------------+------------------+--------------------+--------------+
|  order_source|device_type|payment_method|total_orders|avg_order_value|avg_items_per_order|avg_discount|avg_installments|installment_orders|installment_rate_pct|rank_by_device|
+--------------+-----------+--------------+------------+---------------+-------------------+------------+----------------+------------------+--------------------+--------------+
|email_campaign|     tablet|        paypal|        1769|       25451.48|               1.11|      1315.7|            3.86|              1241|               70.15|             1|
|        direct|     tablet|     apple_pay|         766|       25205.87|                1.1|     1173.27|             3.9|               544|               71.02|             2|
|        direct|     mobile|     apple_pay|        2400|       25180.17|                1.1|     1105.11|            3.94|              1709|               71.21|             1|
|        direct|     mobile|        paypal|        3546|        25026.0|                1.1|     1131.37|             3.9|              2479|               69.91|             2|
|organic_search|     tablet|           cod|        4125|        24988.9|               1.11|     1128.54|             1.0|                 0|                0.00|             3|
|        direct|     tablet|           cod|        1152|       24967.28|               1.09|      1182.6|             1.0|                 0|                0.00|             4|
|        direct|     tablet| bank_transfer|         392|       24920.36|                1.1|     1178.17|            3.79|               271|               69.13|             5|
|        direct|    desktop| bank_transfer|        1045|       24917.09|                1.1|     1108.49|            3.86|               717|               68.61|             1|
|      referral|    desktop|        paypal|        3882|       24858.36|                1.1|     1204.09|            3.98|              2735|               70.45|             2|
|   paid_search|     tablet| bank_transfer|        1077|       24857.03|               1.11|     1216.29|            3.66|               740|               68.71|             6|
|      referral|     tablet|     apple_pay|         958|       24827.75|                1.1|      1174.5|            3.78|               667|               69.62|             7|
|   paid_search|     mobile| bank_transfer|        3213|        24791.8|                1.1|     1188.06|            3.85|              2198|               68.41|             3|
|   paid_search|     tablet|        paypal|        3134|       24668.37|               1.11|     1264.07|            3.85|              2183|               69.66|             8|
|      referral|     mobile|        paypal|        4336|       24655.29|                1.1|     1227.28|            3.81|              2979|               68.70|             4|
|   paid_search|    desktop|           cod|        8374|       24655.09|               1.11|     1182.02|             1.0|                 0|                0.00|             3|
|email_campaign|    desktop| bank_transfer|        1557|       24638.17|               1.12|     1193.43|            3.89|              1099|               70.58|             4|
|   paid_search|     mobile|     apple_pay|        6327|        24590.8|                1.1|     1179.61|            3.88|              4442|               70.21|             5|
|   paid_search|    desktop| bank_transfer|        2868|        24586.8|               1.11|     1107.63|            3.95|              1986|               69.25|             5|
|email_campaign|    desktop|     apple_pay|        3064|       24542.96|                1.1|     1207.73|            3.84|              2098|               68.47|             6|
|email_campaign|     tablet|   credit_card|        6372|       24513.28|               1.11|     1191.33|            3.92|              4484|               70.37|             9|
+--------------+-----------+--------------+------------+---------------+-------------------+------------+----------------+------------------+--------------------+--------------+
only showing top 20 rows

,order_source,device_type,payment_method,total_orders,avg_order_value,avg_items_per_order,avg_discount,avg_installments,installment_orders,installment_rate_pct,rank_by_device
0,email_campaign,tablet,paypal,1769,25451.48,1.11,1315.70,3.86,1241,70.15,1
1,direct,tablet,apple_pay,766,25205.87,1.10,1173.27,3.90,544,71.02,2
2,direct,mobile,apple_pay,2400,25180.17,1.10,1105.11,3.94,1709,71.21,1
3,direct,mobile,paypal,3546,25026.00,1.10,1131.37,3.90,2479,69.91,2
4,organic_search,tablet,cod,4125,24988.90,1.11,1128.54,1.00,0,0.00,3
...,...,...,...,...,...,...,...,...,...,...,...
85,social_media,tablet,cod,2898,23495.90,1.10,1143.43,1.00,0,0.00,27
86,referral,tablet,bank_transfer,471,23449.49,1.14,1127.77,3.88,315,66.88,28
87,email_campaign,tablet,bank_transfer,578,23215.02,1.12,1211.46,3.77,385,66.61,29
88,email_campaign,tablet,apple_pay,1205,23159.47,1.11,1179.55,3.84,833,69.13,30
89,direct,mobile,bank_transfer,1129,23024.08,1.11,1057.97,3.82,796,70.50,30

In [32]:
import os
import matplotlib.pyplot as plt

output_path = "/Users/tranduykhoa/Downloads/Data/results"

os.makedirs(output_path, exist_ok=True)

def export_query_result(result_df, query_name, show_rows=20):
    pdf = result_df.limit(50).toPandas()

    csv_path = f"{output_path}/{query_name}.csv"
    pdf.to_csv(csv_path, index=False, encoding="utf-8-sig")
    print(f"CSV saved: {csv_path}")

    fig, ax = plt.subplots(figsize=(max(10, len(pdf.columns) * 1.5),
                                    min(20, len(pdf) * 0.4 + 1.5)))
    ax.axis("off")
    tbl = ax.table(
        cellText  = pdf.values,
        colLabels = pdf.columns,
        cellLoc   = "center",
        loc       = "center"
    )
    tbl.auto_set_font_size(False)
    tbl.set_fontsize(8)
    tbl.auto_set_column_width(col=list(range(len(pdf.columns))))

    for j in range(len(pdf.columns)):
        tbl[0, j].set_facecolor("#2C3E50")
        tbl[0, j].set_text_props(color="white", fontweight="bold")

    for i in range(1, len(pdf) + 1):
        for j in range(len(pdf.columns)):
            tbl[i, j].set_facecolor("#EAF2FF" if i % 2 == 0 else "white")

    plt.title(query_name.replace("_", " ").upper(),
              fontsize=11, fontweight="bold", pad=12)
    plt.tight_layout()

    img_path = f"{output_path}/{query_name}.png"
    plt.savefig(img_path, dpi=150, bbox_inches="tight")
    plt.close()
    print(f"PNG saved: {img_path}")

    return pdf

all_queries = [
    (result_q1,  "Q01_doanh_thu_theo_thang"),
    (result_q2,  "Q02_khach_hang_theo_kenh"),
    (result_q3,  "Q03_top_san_pham_bien_loi_nhuan"),
    (result_q4,  "Q04_rating_theo_danh_muc"),
    (result_q5,  "Q05_web_traffic_theo_nguon"),
    (result_q6,  "Q06_khach_hang_theo_vung"),
    (result_q7,  "Q07_hieu_qua_khuyen_mai"),
    (result_q8,  "Q08_window_rank_san_pham"),
    (result_q9,  "Q09_rfm_analysis"),
    (result_q10, "Q10_full_pipeline_join"),
    (result_q11, "Q11_inventory_toan_dien"),
    (result_q12, "Q12_cohort_retention"),
    (result_q14, "Q14_funnel_traffic_to_revenue"),
    (result_q15, "Q15_promotion_roi_lift"),
    (result_q16, "Q16_delivery_performance"),
    (result_q17, "Q17_return_analysis"),
    (result_q18, "Q18_payment_intelligence"),
]

📊 Đang xuất Q01_doanh_thu_theo_thang...
✅ CSV saved: /Users/tranduykhoa/Downloads/Data/results/Q01_doanh_thu_theo_thang.csv
✅ PNG saved: /Users/tranduykhoa/Downloads/Data/results/Q01_doanh_thu_theo_thang.png

📊 Đang xuất Q02_khach_hang_theo_kenh...

26/06/13 20:02:56 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
26/06/13 20:02:56 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
26/06/13 20:02:56 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
26/06/13 20:02:57 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
26/06/13 20:02:57 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
26/06/13 20:02:57 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
26/06/13 20:02:57 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.

✅ CSV saved: /Users/tranduykhoa/Downloads/Data/results/Q02_khach_hang_theo_kenh.csv
✅ PNG saved: /Users/tranduykhoa/Downloads/Data/results/Q02_khach_hang_theo_kenh.png

📊 Đang xuất Q03_top_san_pham_bien_loi_nhuan...
✅ CSV saved: /Users/tranduykhoa/Downloads/Data/results/Q03_top_san_pham_bien_loi_nhuan.csv
✅ PNG saved: /Users/tranduykhoa/Downloads/Data/results/Q03_top_san_pham_bien_loi_nhuan.png

📊 Đang xuất Q04_rating_theo_danh_muc...
✅ CSV saved: /Users/tranduykhoa/Downloads/Data/results/Q04_rating_theo_danh_muc.csv
✅ PNG saved: /Users/tranduykhoa/Downloads/Data/results/Q04_rating_theo_danh_muc.png

📊 Đang xuất Q05_web_traffic_theo_nguon...
✅ CSV saved: /Users/tranduykhoa/Downloads/Data/results/Q05_web_traffic_theo_nguon.csv
✅ PNG saved: /Users/tranduykhoa/Downloads/Data/results/Q05_web_traffic_theo_nguon.png

📊 Đang xuất Q06_khach_hang_theo_vung...

26/06/13 20:02:58 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
26/06/13 20:02:58 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
26/06/13 20:02:58 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
26/06/13 20:02:58 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
26/06/13 20:02:59 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
26/06/13 20:02:59 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
26/06/13 20:02:59 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
26/06/13 20:02:59 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.

✅ CSV saved: /Users/tranduykhoa/Downloads/Data/results/Q06_khach_hang_theo_vung.csv
✅ PNG saved: /Users/tranduykhoa/Downloads/Data/results/Q06_khach_hang_theo_vung.png

📊 Đang xuất Q07_hieu_qua_khuyen_mai...

26/06/13 20:03:00 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
26/06/13 20:03:00 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
26/06/13 20:03:00 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
26/06/13 20:03:00 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
26/06/13 20:03:00 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
26/06/13 20:03:00 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
26/06/13 20:03:00 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
26/06/13 20:03:00 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
26/06/13 20:03:01 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
26/06/13 20:03:01 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
26/06/13 20:03:01 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
26/06/13 20:03:01 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
26/06/13 20:03:01 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
26/06/13 20:03:01 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
26/06/13 20:03:01 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
26/06/13 20:03:01 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.

✅ CSV saved: /Users/tranduykhoa/Downloads/Data/results/Q07_hieu_qua_khuyen_mai.csv
✅ PNG saved: /Users/tranduykhoa/Downloads/Data/results/Q07_hieu_qua_khuyen_mai.png

📊 Đang xuất Q08_window_rank_san_pham...

✅ CSV saved: /Users/tranduykhoa/Downloads/Data/results/Q08_window_rank_san_pham.csv
✅ PNG saved: /Users/tranduykhoa/Downloads/Data/results/Q08_window_rank_san_pham.png

📊 Đang xuất Q09_rfm_analysis...
✅ CSV saved: /Users/tranduykhoa/Downloads/Data/results/Q09_rfm_analysis.csv
✅ PNG saved: /Users/tranduykhoa/Downloads/Data/results/Q09_rfm_analysis.png

📊 Đang xuất Q10_full_pipeline_join...
✅ CSV saved: /Users/tranduykhoa/Downloads/Data/results/Q10_full_pipeline_join.csv
✅ PNG saved: /Users/tranduykhoa/Downloads/Data/results/Q10_full_pipeline_join.png

📊 Đang xuất Q11_inventory_toan_dien...
✅ CSV saved: /Users/tranduykhoa/Downloads/Data/results/Q11_inventory_toan_dien.csv

26/06/13 20:03:07 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
26/06/13 20:03:07 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
26/06/13 20:03:07 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
26/06/13 20:03:07 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
26/06/13 20:03:07 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.

✅ PNG saved: /Users/tranduykhoa/Downloads/Data/results/Q11_inventory_toan_dien.png

📊 Đang xuất Q12_cohort_retention...
✅ CSV saved: /Users/tranduykhoa/Downloads/Data/results/Q12_cohort_retention.csv
✅ PNG saved: /Users/tranduykhoa/Downloads/Data/results/Q12_cohort_retention.png

📊 Đang xuất Q14_funnel_traffic_to_revenue...
✅ CSV saved: /Users/tranduykhoa/Downloads/Data/results/Q14_funnel_traffic_to_revenue.csv
✅ PNG saved: /Users/tranduykhoa/Downloads/Data/results/Q14_funnel_traffic_to_revenue.png

📊 Đang xuất Q15_promotion_roi_lift...
✅ CSV saved: /Users/tranduykhoa/Downloads/Data/results/Q15_promotion_roi_lift.csv
✅ PNG saved: /Users/tranduykhoa/Downloads/Data/results/Q15_promotion_roi_lift.png

📊 Đang xuất Q16_delivery_performance...

✅ CSV saved: /Users/tranduykhoa/Downloads/Data/results/Q16_delivery_performance.csv
✅ PNG saved: /Users/tranduykhoa/Downloads/Data/results/Q16_delivery_performance.png

📊 Đang xuất Q17_return_analysis...

✅ CSV saved: /Users/tranduykhoa/Downloads/Data/results/Q17_return_analysis.csv
✅ PNG saved: /Users/tranduykhoa/Downloads/Data/results/Q17_return_analysis.png

📊 Đang xuất Q18_payment_intelligence...

✅ CSV saved: /Users/tranduykhoa/Downloads/Data/results/Q18_payment_intelligence.csv
✅ PNG saved: /Users/tranduykhoa/Downloads/Data/results/Q18_payment_intelligence.png

🎉 Hoàn tất! Kiểm tra thư mục: /Users/tranduykhoa/Downloads/Data/results